### ISSUE TITLE
Screen Share Audio not triggering on mobile browser

### ISSUE THREAD

**Issue by eyupduran** [livekit/client-sdk-js#1031]
### Describe the bug

I'm building an Angular app using LiveKit client JS to broadcast music with ScreenShareAudio. It works well on desktop browsers but doesn't trigger the screen selection interface on mobile browsers, thus ScreenShareAudio doesn't function. Do mobile browsers not support screen sharing or ScreenShareAudio?

### Reproduction

I'm developing an Angular application that utilizes LiveKit client JS for broadcasting music with ScreenShareAudio functionality. While this works seamlessly on desktop browsers, I encountered an issue on mobile browsers. When attempting to trigger the createScreenTracks function, the interface to select screens fails to open, leading to the failure of ScreenShareAudio functionality.

This raises the question: do mobile browsers lack support for screen sharing or ScreenShareAudio features? It seems that the standard behavior observed on desktop browsers isn't replicated on mobile platforms. Understanding the limitations or potential workarounds for mobile browsers in this context would be crucial for ensuring consistent functionality across different devices and browsers

### Logs

```shell
no log
```

### System Info

```shell
Android 11,Chrome Mobile browser 121.0.6167.164
```

### Severity

annoyance

**Comment by lukasIO** [comment]
> do mobile browsers lack support for screen sharing or ScreenShareAudio features?

yeah, unfortunately that is the case. Mobile browsers don't allow screen sharing
