### ISSUE TITLE
Room.Reconnecting event does not fire after update to v2.0.3

### ISSUE THREAD

**Issue by revertiz** [livekit/client-sdk-js#1046]
### Describe the bug

We had logic to display "reconnecting" information to user that was dependant on Room.Reconnecting event. It appears that after client-sdk-js version 2.0.0 the event is no longer emitted in this case (case being turning off internet connection and waiting). Is this intended change by this PR: https://github.com/livekit/client-sdk-js/pull/1012 ? If so, is there other intended way to handle this?

### Reproduction

1. turn off internet connection
2. wait
3. result no Room.Reconnecting event fired until i turn internet connection back on

### System Info

```shell
System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M1
    Memory: 113.53 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node
    Yarn: 3.6.3 - ~/.yarn/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.0/bin/npm
    pnpm: 8.14.2 - ~/.nvm/versions/node/v18.17.0/bin/pnpm
  Browsers:
    Brave Browser: 117.1.58.137
    Chrome: 121.0.6167.184
    Safari: 17.2.1
  npmPackages:
    livekit-client: ^2.0.3 => 2.0.3
```

### Severity

annoyance

**Comment by lukasIO** [comment]
The `Reconnecting` event will still fire, it will just take a little longer until this state is triggered.

**Comment by revertiz** [comment]
> The `Reconnecting` event will still fire, it will just take a little longer until this state is triggered. Are you saying it will never emit even after a longer period of time without internet connection?

As long as I keep the internet connection turned off, i don't get the event. It fires after I turn on the internet connection, though

**Comment by lukasIO** [comment]
that's unexpected, how long do you usually wait until you turn the internet connection back on?

**Comment by lukasIO** [comment]
Ok confirmed that this is an issue, thanks for the report, the current behaviour you're observing is not the intended behaviour.

**Comment by revertiz** [comment]
> that's unexpected, how long do you usually wait until you turn the internet connection back on?

any amount of time, up until the peer connection to server closes entirely, 10s-60s
