### ISSUE TITLE
LocalTrack doesn't remove event listener when unpublished

### ISSUE THREAD

**Issue by lukasIO** [livekit/client-sdk-js#106]
https://github.com/livekit/client-sdk-js/blob/ae849e477a8a20f07f362313af057262badc0455/src/room/track/LocalTrack.ts#L19

Adds an 'ended' event to the underlying mediatstreamtrack that doesn't get removed.

Maybe a dispose function for the track that (for now) only removes this event listener and is called on track unpublish?

**Comment by davidzhao** [comment]
The 'ended' listener is supposed to be there as long as the LocalTrack claims ownership over the MediaStreamTrack.

I think the only thing missing is this line in your PR

```
track.off(TrackEvent.Ended, this.onTrackUnpublish);
```

When unpublished, the Publication object should no longer care about events that LocalTrack is firing.

**Comment by lukasIO** [comment]
There is currently one situation in which that line gets called and that's the `unpublishTrack `function of the `LocalParticipant`:

https://github.com/livekit/client-sdk-js/blob/f5e69ed6255aff01af1b900f6fb5f1d78ecc5e7f/src/room/participant/LocalParticipant.ts#L453

I used an override on the `LocalTrack `to subscribe and unsubscribe to the underlying mediatrack 'ended' event when the livekit `TrackEvent.Ended` is being subscribed/unsubscribed
https://github.com/livekit/client-sdk-js/blob/f5e69ed6255aff01af1b900f6fb5f1d78ecc5e7f/src/room/track/LocalTrack.ts#L127-L141

**Comment by davidzhao** [comment]
I see that line.. but not convinced why this is necessary. A LocalTrack, even when unpublished, should listen to the underlying MediaStreamTrack events.

**Comment by lukasIO** [comment]
Hm, I guess you are right. On top it now seems like a rather stupid idea of me to add the same event handler to the mediaStreamTrack each time TrackEvent.Ended is being subscribed to.

Then the only question remains when to actually remove the event listener from the mediaStreamTrack. 
Should I reconsider adding a `dispose` function to LocalTrack?

**Comment by davidzhao** [comment]
I still think we'd only need to update listener to `TrackEvent.Ended` inside `LocalTrackPublication.setTrack` and `LocalParticipant.unpublishTrack`:

i.e.

```
track.off(TrackEvent.Ended, this.onTrackUnpublish);
```

MediaStreamTrack isn't supposed to be reused across other LocalTracks, as long as the LocalTrack itself is re-usable.

**Comment by lukasIO** [comment]
> I still think we'd only need to update listener to TrackEvent.Ended inside LocalTrackPublication.setTrack and LocalParticipant.unpublishTrack

Maybe I'm misunderstanding something.
What would you want to do with TrackEvent.Ended inside LocalTrackPublication? 

But TrackEvent.Ended event on the Track itself should persist independently from the TrackPublication, right? 

My understanding is: 
LocalTrack:
- holds mediaStreamTrack and listens to mediaStreamTrackEvents
- emits TrackEvents
- lives independently from publications

LocalTrackPublication
- subscribes to TrackEvents
- unpublishing doesn't affect the underlying LocalTrack

I'll update my PR to remove unnecessary changes and will try to address the reasoning for the remaining ones in code comments.
