### ISSUE TITLE
Audio elements cannot be initialized when a Livekit connection is established without user interaction

### ISSUE THREAD

**Issue by eyupduran** [livekit/client-sdk-js#1089]
### Describe the bug

I cannot get the voices of the existing participants when I do these operations without any interaction from the user to set up the Livekit connection and enter the room. I think it's a browser. How can I solve this situation in Livekit ?

### Reproduction

When I attempt to establish a Livekit connection directly via a link, without any user interaction (such as clicking a button), I am unable to receive any audio. This entry is made with a URL. When I try to do this using JavaScript click events, I still cannot receive audio. The browser console logs the following error:

The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page

### Logs

```shell
The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page
```

### System Info

```shell
Windows 11 pro, 123.0.6312.58
```

### Severity

annoyance

**Comment by lukasIO** [comment]
you'll have to call `room.startAudio()` directly from a user's gesture, e.g. a click handler
