### ISSUE TITLE
iOS: Can't see remote participant camera feed (chrome)

### ISSUE THREAD

**Issue by AurimasG12** [livekit/client-sdk-js#1094]
### Describe the bug

I should see remote participant camera feed, but at the moment - remote participant camera feed is muted.

### Reproduction

- Open https://meet.livekit.io/ with computer
- Create room with enabled end to end encryption
- Join room
- Pick up iphone  <= 13 or simulator (browserstack) and choose iOS version 15 and open chrome
- Try to join same room as in computer 
- Accept permissions

I used real Iphone 8 with iOs 16.7. Also reproduced this case with Iphone iOs 15 simulator in browserstack.

### System Info

```shell
Iphone 8 with iOs 16.7.
Iphone 13 simulator with iOs 15

Browser: chrome
```

### Severity

blocking all usage of LiveKit

**Comment by davidzhao** [comment]
when E2EE is enabled, the encryption key is part of Meet's URL. you need to copy that URL exactly onto the mobile device. Otherwise it's expected the other side cannot decode any of the video.

**Comment by AurimasG12** [comment]
> when E2EE is enabled, the encryption key is part of Meet's URL. you need to copy that URL exactly onto the mobile device. Otherwise it's expected the other side cannot decode any of the video.

I've joined with password

**Comment by arnasledev** [comment]
Reproducing also. Using https://meet.livekit.io 

![image](https://github.com/livekit/client-sdk-js/assets/39725714/c5a20eb0-f491-4450-9e78-ef6eb1abe0ef)
![image](https://github.com/livekit/client-sdk-js/assets/39725714/1c9d7549-9778-4957-aa05-62b526dba02f)
