### ISSUE TITLE
 Invalid codec preferences: invalid codec with name "AV1".

### ISSUE THREAD

**Issue by mohammad19974** [livekit/client-sdk-js#1111]
### Describe the bug

DOMException: Failed to execute 'setCodecPreferences' on 'RTCRtpTransceiver': Invalid codec preferences: invalid codec with name "AV1".
    at RTCEngine.setPreferredCodec /deps/chunk-LWCD622N.js?v=5bf620e7:14366:19)
    at Generator.next (<anonymous>)
    at fulfilled (http://localhost:3000/.vite/deps/chunk-LWCD622N.js?v=5bf620e7:4534:24)

### Reproduction

when run camera show this we can't on chrome 
Chrome is up to date
Version 124.0.6367.61 (Official Build) (64-bit
last Version it's work but 124.0.6367.61 not work ,
i used livekit-client 1.5.13 

### System Info

```shell
Chrome is up to date
Version 124.0.6367.61 (Official Build) (64-bit
```

### Severity

annoyance

**Comment by robintown** [comment]
This Chrome 124 compatibility issue mentioned on the LiveKit Slack is most likely what you're running into:

> Important Update: Upgrade LiveKit SDK for Chrome 124 Compatibility :rotating_light:We've got an urgent update for everyone building browser-based apps. With Chrome 124 releasing on April 16th, there's a breaking change in the setCodecPreferences API that affects our [SDKs.Here](http://sdks.here/)'s what you need to do:
> Upgrade your LiveKit Client SDK to these versions before April 10th to avoid any breakage:
> • Web: v2.0.10 or v1.15.13
> • Flutter: v2.0.3
> • Unity Web: v1.5.1
> • React: v2.0.5
> Please prioritize this update to ensure your applications continue to work seamlessly with this new version of Chrome. If you encounter any issues or have questions, please let us know in the :thread: .Thanks for acting swiftly on this!-The LiveKit Team

**Comment by lukasIO** [comment]
@manaclan could you open a separate issue about this with some steps to reproduce it? thanks!

**Comment by giantninja** [comment]
I am seeing the same issue, and my livekit frontend app is based on the older version of the react example app, so updating isn't super straightforward.  I have been trying to set the codec in the roomOptions but this doesn't seem to be working:

```
publishDefaults: {
  videoCodec: 'vp8',
  backupCodec: { codec: 'h264', encoding: { maxBitrate: 1_700_000 } },
}
```

Is there a work around that can be implemented in-code without updating?  Or is updating the only way to fix that error?

Here are the versions I'm using:
```
"livekit-client": "^1.7.0",
"@livekit/react-core": "^1.1.0",
"react": "^18.2.0",
```

**Comment by davidzhao** [comment]
can you try using `livekit-client: 1.15.13` ? this update is required, but 1.15.13 is API compatible with v1 clients.

**Comment by giantninja** [comment]
Thank you @davidzhao, that looks like it solves this issue.  Much appreciated :)

**Comment by MarcoMayCry** [comment]
nice work👍 Thanks
