### ISSUE TITLE
Error "Cannot read properties of undefined (reading 'size')" when Participant leaves

### ISSUE THREAD

**Issue by longlwu2000** [livekit/client-sdk-js#1129]
### Describe the bug

Error "Cannot read properties of undefined (reading 'size')" when Participant leaves

![image](https://github.com/livekit/client-sdk-js/assets/99626338/38db2988-ff07-4d4a-8ed9-3b8862d01407)

![image](https://github.com/livekit/client-sdk-js/assets/99626338/ed26b582-afcc-4341-b41e-7dd131d56a35)

### Reproduction

I encounter this error every time a user leaves the room.

### System Info

```shell
Chrome Version 124.0.6367.119 (64-bit)
```

### Severity

serious, but I can work around it

**Comment by lukasIO** [comment]
Is this a recent version? The API changed and you have to use `room.remoteParticipants` now. See [migration guide](https://docs.livekit.io/guides/migrate-from-v1/)

**Comment by longlwu2000** [comment]
The error appears in the source code of the package @livekit/egress-sdk. I tried installing this package with the command: 'npm i @livekit/egress-sdk@latest'. In the package.json, it shows version 0.2.0. Is this the latest version?

![Screenshot 2024-05-07 094340](https://github.com/livekit/client-sdk-js/assets/99626338/d79b63cb-bf9d-49f4-aa97-89ef607fa46b)

![image](https://github.com/livekit/client-sdk-js/assets/99626338/e8d8aa75-7463-47be-94c8-174b9a699fdc)
