### ISSUE TITLE
Problem of No Sound Sometimes in Chrome on IOS

### ISSUE THREAD

**Issue by eyupduran** [livekit/client-sdk-js#1133]
### Describe the bug

I can't hear audio from users with active microphones when navigating between rooms in the audio and video chat application on iOS Chrome browser. This issue only occurs on iOS Chrome. I've updated Livekit's version, but the problem persists

### Reproduction

In the audio chat application, there are multiple rooms available, and users sometimes experience audio issues when switching between rooms, especially on iOS Chrome browser. Specifically, I can't hear users with active microphones intermittently. This problem seems to occur exclusively on iOS Chrome, as there are no issues on other platforms such as Chrome desktop or Android Chrome. I upgraded the Livekit client JS package from version 1.15.13 to 2.1.3, but it didn't resolve the issue. How can I fix this problem?

### System Info

```shell
Iphone 12 Pro,Chrome(124.0.6367.111)
```

### Severity

annoyance

### Additional Information
The device joining the room with iOS that cannot receive audio triggers the RoomEvent.ParticipantConnected event, and additionally, the audio indicator for the participant with an active microphone in the room keeps flashing, even though there is no audio coming from the room. So, it seems there's no issue with the Livekit connection.
_No response_

**Comment by lukasIO** [comment]
Are you handling the `RoomEvent.AudioPlaybackStatusChanged` event?

**Comment by eyupduran** [comment]
No, I don't handling this Event. What exactly should I do in this event?

**Comment by lukasIO** [comment]
if audio playback failed you should show a button with a click handler that calls `room.startAudio()`, see also the docs [here](https://docs.livekit.io/client-sdk-js/classes/Room.html#startAudio)

**Comment by eyupduran** [comment]
In fact, I am building a room connection with user interaction. Doesn't this automatically trigger Room.startaudio?

**Comment by lukasIO** [comment]
it should, but it's not guaranteed. Listen to the event I mentioned to make sure that audio playback isn't blocked

**Comment by eyupduran** [comment]
okey, yhanks for your interest
