### ISSUE TITLE
`livekit-client` v2.1.2 breaks React Native compatibility

### ISSUE THREAD

**Issue by ariboren** [livekit/client-sdk-js#1134]
### Describe the bug

Commit [a087e036be1286a7bbf10b72aaaf6b261b70fa3f](https://github.com/livekit/client-sdk-js/commit/a087e036be1286a7bbf10b72aaaf6b261b70fa3f#diff-d844533d54d1e1cedf8ed4b95a2eebeea4035b2ff72b21e89cb655edb7f0154fR88) adds a call to `receiver.getSynchronizationSources()`, which does not exist on [`RTCRtpReceiver` in React Native](https://github.com/livekit/react-native-webrtc/blob/master/src/RTCRtpReceiver.ts), resulting in runtime errors.

### Reproduction

In a React Native application:
1. Install `livekit-client >2.1.1`, `@livekit/react-native-webrtc latest` (currently 114.1.2), and `@livekit/react-native 2.1.1`.
2. Attempt to subscribe to remote track.

### Logs

```shell
ERROR  TypeError: i.getSynchronizationSources is not a function (it is undefined), js engine: hermes
```

### System Info

```shell
@livekit/react-native@2.1.1
@livekit/react-native-expo-plugin@1.0.0
@livekit/react-native-webrtc@114.1.2
livekit-client@2.1.3
```

### Severity

blocking an upgrade

**Comment by lukasIO** [comment]
thanks for the report! Opened https://github.com/livekit/client-sdk-js/pull/1136 to address this

**Comment by davidliu** [comment]
Unfortunately looks like there's no direct equivalent on the native side for this method. I think we might be able to get the ssrc timestamps from the stats objects, but it's a little sketchy there.
