### ISSUE TITLE
Audio-only mode

### ISSUE THREAD

**Issue by shya-me** [livekit/client-sdk-js#1147]
### Describe the problem

Is there a way to use Audio-only mode? I don't want to allow participants to share the screen or video.

### Describe the proposed solution

The Audio-only mode would like a conference-call in the presence of AI, maybe?

### Importance

I cannot use LiveKit without it

**Comment by lukasIO** [comment]
on a token level you can set this with `canPublishSources`, have a look at the documentation [here](https://docs.livekit.io/home/get-started/authentication/#Example-camera-only)
