### ISSUE TITLE
Room Reconnected event doesn't get emitted

### ISSUE THREAD

**Issue by revertiz** [livekit/client-sdk-js#1163]
### Describe the bug

When i have a bad internet connection the room reconnect event is not completely reliable

### Reproduction

Reproducibility <50%: 
1. Turn off internet for a longer period, get the reconnecting event  
2. Turn on internet for a short duration (1-3s), get the reconnected event 
3. Turn off internet for a longer period, get the reconnecting event 
4. Turn on internet, i can see other participant, but don't get the reconnected event

### Logs

[client-ignasp-local.front-4877.pr.meedio.pro-1718225459290.log](https://github.com/user-attachments/files/15810958/client-ignasp-local.front-4877.pr.meedio.pro-1718225459290.log)
[server-ignasp-local.front-4877.pr.meedio.pro-1718225459290.json](https://github.com/user-attachments/files/15810959/server-ignasp-local.front-4877.pr.meedio.pro-1718225459290.json)

### System Info

```shell
System:
    OS: macOS 14.4.1
    CPU: (8) arm64 Apple M1
    Memory: 106.47 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node
    Yarn: 4.0.2 - ~/.yarn/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.0/bin/npm
    pnpm: 8.14.2 - ~/.nvm/versions/node/v18.17.0/bin/pnpm
  Browsers:
    Brave Browser: 117.1.58.137
    Chrome: 125.0.6422.142
    Safari: 17.4.1
  npmPackages:
    livekit-client: ^2.2.0 => 2.2.0
```

### Severity

annoyance

### Additional Information

In the client logs there's my added log "timer ran out roomStateRef.current: disconnected"(timer runs out, because it didn't receive the reconnected event and didn't get cleared). It seems that the room ConnectionState is 'disconnected' even though both participants can see each other.

**Comment by lukasIO** [comment]
How are you disabling your internet connection? 
And is your server running locally?

**Comment by revertiz** [comment]
> How are you disabling your internet connection? And is your server running locally?

-I disable by just turning off WiFi completely (clicking toggle in macOS)
- Server is running remotely

**Comment by lukasIO** [comment]
Thanks. 
In the logs you shared, I can see both 
```
23:50:11.361 livekit-client.esm.mjs:21326 room event reconnected {room: '!NeGhSXJYtaMmIgxgIk:matrix.meedio.pro', roomID: 'RM_o4Tt2VegfDwU', participant: '@cw4s1ohjnb:matrix.meedio.pro:VSIPQLWNPN', pID: 'PA_DJBmpTmFjqGG', event: 'reconnected', …}

```

and, a little earlier 
```
23:50:11.361 useHandleLivekitReconnection.ts:54 ConnectionStateChanged event connected
```
which sounds like your logic around this picked up on connectionState changing back to `connected`

**Comment by romancavry** [comment]
@lukasIO 

I get this error on `2.5.0` package version.

The case is similar to @revertiz. The call is started, but then call's receiver disconnects due to network issue. At the same time caller hangs up. A bit later (30-45s after disconnect) the receiver's network starts working, but he gets not emitted `reconnected` event instead of `disconnected`.

This receiver's logs:
<img width="569" alt="SD-3966 (logs)" src="https://github.com/user-attachments/assets/e155f38c-abf9-473e-bbb5-4d0633836493">

**Comment by lukasIO** [comment]
this is probably because the room has cleared after 20s without anyone inside

**Comment by romancavry** [comment]
> this is probably because the room has cleared after 20s without anyone inside

what is the best approach here? Timeout?

**Comment by lukasIO** [comment]
probably to handle the unintended disconnect by attempting to re-initiate connection to the room

**Comment by romancavry** [comment]
> probably to handle the unintended disconnect by attempting to re-initiate connection to the room

is there any reconnect method?  
In general, it would be useful to get `disconnected` event with `ROOM_DELETED` reason instead of `reconnected` :/
