### ISSUE TITLE
How to check participation's camera or microphone is enabled?

### ISSUE THREAD

**Issue by oldner** [livekit/client-sdk-js#119]
Hi,

I am having an issue for 2 days. What I am trying to do is accessing participant's isCameraEnabled, isMicrophoneEnabled variables. Because those created as get method, it does not return true when I want to check.  

in participantConnected(participant: Participant) method, I am trying to console log participant.isMicrophoneEnabled. It returns false. But I already connected with enable cam and mic. Also if I make isMicrophoneEnabled true on Vue chrome extension, I can see my video on the screen. I also put some consoles in node_modules\livekit-client\dist\room\participant\Participant.js to see if it is triggered. 

```
...
console.log(participant.isMicrophoneEnabled) // returns false
console.log(participant) //
...
```

node_modules\livekit-client\dist\room\participant\Participant.js
![image](https://user-images.githubusercontent.com/48028389/149349687-b6d2ee7f-2baa-4663-8500-548d9b5a176c.png)

Both console logs do not works until I click the participant's isCameraEnabled on console (You can see the image below.) 

Step 1
![image](https://user-images.githubusercontent.com/48028389/149350189-6f3d9004-b824-403d-a58d-e7bb5a3399b0.png)

Step 2 - After I clicked (...) next to isCameraEnabled
![image](https://user-images.githubusercontent.com/48028389/149350279-aeedd366-e543-4b2a-b03e-ddd478851505.png)

![image](https://user-images.githubusercontent.com/48028389/149350464-ab3bcbff-2c8f-4bc2-b90d-87568b534e50.png)

I also tried to use room.participants.get('participant.sid') but it does not initialized in participantConnected func. I can also use this one if it will work. 

Thanks

**Comment by davidzhao** [comment]
when you checked for `isCameraEnabled`, it hasn't finished enabling at the time console.log ran.

The reason why you can see it later is because when you clicked on (...), the function executed then.
