### ISSUE TITLE
Support for more encryption algorithms for e2ee

### ISSUE THREAD

**Issue by zesun96** [livekit/client-sdk-js#1190]
### Describe the problem

I tested more encryption algorithms and e2ee run very well but sdk only support AES-GCM. 
But I guess adding it to the SDK is difficult because it's not natively supported by the browser.
If there are ideas to support a lot of algorithms, or some suggestions for modifications, I can help.

### Describe the proposed solution

 support a lot of algorithms.

### Importance

nice to have

**Comment by lukasIO** [comment]
Hi, 
there are currently no plans to add any other encryption algorithms.
