### ISSUE TITLE
Invalid codec preferences: invalid codec with name "H264"

### ISSUE THREAD

**Issue by dkarpov-w** [livekit/client-sdk-js#1219]
### Describe the bug

DOMException: Failed to execute 'setCodecPreferences' on 'RTCRtpTransceiver': Invalid codec preferences: invalid codec with name "H264".
    at RTCEngine.setPreferredCodec (webpack-internal:///(app-pages-browser)/./node_modules/livekit-client/dist/livekit-client.esm.mjs:17454:19)
    at RTCEngine.eval (webpack-internal:///(app-pages-browser)/./node_modules/livekit-client/dist/livekit-client.esm.mjs:17503:14)
    at Generator.next (<anonymous>)
    at fulfilled (webpack-internal:///(app-pages-browser)/./node_modules/livekit-client/dist/livekit-client.esm.mjs:6215:58)

### Reproduction

Do next 
`vv`
```
const res = await navigator.mediaDevices.getUserMedia({ video: true, audio: false });

......
<LiveKitRoom
      video={false}
       audio={true}
       token={token}
       connect={connectToLiveKit}
       serverUrl={process.env.NEXT_PUBLIC_LIVEKIT_URL}
        className='w-full h-full'
        data-lk-theme='disable'>
              <VideoRoom 
                    loading={loading}
                    startMatch={startmatch}
                    stopAllMatching={stopAllMatching}
                    mediaStream={mediaStream} />
</LiveKitRoom>
                    
 ......
  useEffect(() => {
        const connect = async () => {
            if (connectionState === 'connected' && mediaStream) {
                try {
                    const localVideoTrack = new LocalVideoTrack(mediaStream!.getVideoTracks()[0]);
                    await localParticipant.localParticipant.publishTrack(localVideoTrack);
                } catch (e) {
                    console.error(e);
                }
            }
        };
        connect();
    }, [connectionState]);
```

### System Info

```shell
Try on Chrome, Opera, Edge
livekit-client - 1.15.4
```

### Severity

annoyance

**Comment by davidzhao** [comment]
you'd need to update your SDK to a more recent version. this is an old bug.
