### ISSUE TITLE
Audio Playback Stops After Removing Default Bluetooth Device

### ISSUE THREAD

**Issue by wezerr** [livekit/client-sdk-js#1220]
### Case:
Connect a new device, such as Bluetooth headphones (the system should set it as the default device).
The device connects, and we can hear everyone properly, and they can hear us.
Remove the device.
The system switches to a new device, and we stop hearing others.
### Expected Behavior: 
After removing the device, the system should correctly switch to another available device and continue to playback sound.
### Actual Behavior:
After removing the device, the system switches to a new device, but we stop hearing others.

### Reproduction

Connect a new Bluetooth device (e.g., headphones).
Ensure the device is set as default and audio is working correctly.
Remove the device.
Observe that audio playback stops.

### System Info

```shell
Operating System: Windows 10
Application Version: LiveKit 2.4.2
Additional Settings: webAudioMix: true
```

### Severity

blocking all usage of LiveKit

**Comment by lukasIO** [comment]
Is this reproducible only with `webAudioMix: true` ? 
What's the behaviour with `webAudioMix: false` ?

**Comment by wezerr** [comment]
We conducted further testing and here are the results:

User1:

Device: AirPods, Windows 11
Case 1:

Enter without headphones, then connect them:
When connecting the headphones, the participant's input device remains the same until the microphone is manually switched.
After disconnecting the headphones, everything becomes correct.
Case 2:

Enter with headphones, disconnect them, and then reconnect them:
After disconnecting, everything works fine, but when reconnecting, the same issue as in Case 1 occurs.
Case 3:

Enter with headphones and change the default device from headphones to system devices:
After changing, the microphone does not switch and remains as the headphone microphone, even though it should have switched to the system microphone.
User2:

Device: Bluetooth headphones, Windows 10
General Case:

Enter without headphones, then connect them:
When connecting the headphones, the participant loses sound and cannot hear anyone.
This issue occurs with webAudioMix set to both true and false.
All cases from User1 are reproducible for User2 as well.

Additionally, I am attaching two log files from the /sample app that were captured during these tests.

Please let me know if you need any further information.
[user2.log](https://github.com/user-attachments/files/16624422/user2.log)
[user1.log](https://github.com/user-attachments/files/16624426/user1.log)

**Comment by lukasIO** [comment]
> This issue occurs with webAudioMix set to both true and false.

how about case 1 and 2 ?

**Comment by wezerr** [comment]
For сases 1 and 2, the value of webAudioMix (whether set to true or false) does not have any impact on the issue. The problems described occur regardless of the webAudioMix setting.

**Comment by lukasIO** [comment]
sorry for the delay, could you try with https://github.com/livekit/client-sdk-js/pull/1237 to see if this fixes the issue you're seeing?

**Comment by Sergwez** [comment]
The bugs from [cases ](https://github.com/livekit/client-sdk-js/issues/1220#issuecomment-2291066793)1, 2, and 3 persist as before; we have tested this with several users.
In the interface, the device (microphone) changes after connecting a new one, but in reality, the person continues to use the old microphone.
The case with the removal of the device (the problem described at the very beginning) now works correctly.

**Comment by wezerr** [comment]
The bugs from https://github.com/livekit/client-sdk-js/issues/1220#issuecomment-22910667931, 2, and 3 persist as before; we have tested this with several users.
In the interface, the device (microphone) changes after connecting a new one, but in reality, the person continues to use the old microphone.
The case with the removal of the device (the problem described at the very beginning) now works correctly.

**Comment by lukasIO** [comment]
thanks for confirming! <br>Cases 1,2,3 are not something we have control over from within the browser, so this is working as intended if the bug at the top of the issue is fixed
