### ISSUE TITLE
Source maps included in npm publication but src files not included leading to warnings in tools like Webpack

### ISSUE THREAD

**Issue by iamahumanbeing** [livekit/client-sdk-js#123]
The npmignore file excludes the src folder (for good reason) but the npm build includes source maps. This leads to many warnings in Webpack that source files are missing. 

If you could either exclude source maps when publishing to npm or include src folder, that would be very helpful. thank you.

**Comment by davidzhao** [comment]
that makes sense! we'll publish the src folder as well in the next version

**Comment by davidzhao** [comment]
resolved in 4a4bf54618a3defa6f2d1adc79630b476a99a90f
