### ISSUE TITLE
Publish tracks from any source

### ISSUE THREAD

**Issue by Green9912** [livekit/client-sdk-js#1308]
### Describe the problem

Does sdkjs support publishing audio data to the room and then playing back the audio? This audio may be a blob object. Room recording can record the content of this audio playback.
Can I choose not to use shared desktop?

### Describe the proposed solution

First, I tested the blob audio object to be converted to MediaStreamTrack and then published tracks from any source. I found that the blob audio could not be converted to MediaStreamTrack and the tracks could not be sent successfully. In the future, I sent a MediaStreamTrack for test, but the room could not receive this MediaStreamTrack and play it as audio. Is there any solution

`//Publish tracks code
const blob = await this.fetchAudio();
      console.log("blob", blob)
      const audioUrl = URL.createObjectURL(blob);
      console.log("audioUrl", audioUrl)
      this.audioPlayer = audioUrl;
      const audioSource = AudioMixerPlugin.createAudioSource({url: audioUrl})
      console.log("audioSource", audioSource)
      const destination = audioSource.destination
      console.log("destination", destination)
      const mediaStream = destination.stream;
      console.log("mediaStream", mediaStream)
      const audioTracks = mediaStream.getAudioTracks();
      console.log("audioTracks", audioTracks)
      const audioTrack = audioTracks[0]; 
      console.log("audioTrack", audioTrack)
      const pub = await this.room.localParticipant.publishTrack(audioTrack, {
        name: 'mytrack',
        simulcast: true,
        source: 'microphone',
      });

//Monitor code
this.room.on(LivekitClient.RoomEvent.TrackPublished, function (track) {
        console.log("track",track)
        const audioElement = new Audio();
        console.log("track",track.track)  //This prints as null
        const stream = new MediaStream([track.track]);
        audioElement.srcObject = stream;
        audioElement.play().catch(error => {
          console.error('Error playing audio track:', error);
        });
      })`

### Importance

nice to have

### Additional Information

//Publish tracks code
![image](https://github.com/user-attachments/assets/e73cd584-5094-4c71-800c-60d745fe0e1e)
![image](https://github.com/user-attachments/assets/c9a9b3ee-211a-47cb-9588-22c4668d5b8e)

//Monitor code
![image](https://github.com/user-attachments/assets/29345f34-636b-4d8b-8188-fbb3f2fb39ee)
![image](https://github.com/user-attachments/assets/beaded74-d1d9-4754-b2d6-3242a0e5094a)

**Comment by lukasIO** [comment]
the sending part looks right, for receiving you'll want to listen to `RoomEvent.TrackSubscribed` and for ease of use simply call `track.attach(myHTMLAudioElement)`
