### ISSUE TITLE
connection quality is not firing also not accurate (always excellent)

### ISSUE THREAD

**Issue by boussaidev** [livekit/client-sdk-js#1311]
### Describe the bug

i think this event is not working also the connection quality is not accurate always "excellent"
  private handleConnectionQualityUpdate = (update: ConnectionQualityUpdate) => {
    update.updates.forEach((info) => {
      if (info.participantSid === this.localParticipant.sid) {
        this.localParticipant.setConnectionQuality(info.quality);
        return;
      }
      const participant = this.getRemoteParticipantBySid(info.participantSid);
      if (participant) {
        participant.setConnectionQuality(info.quality);
      }
    });
  };

### Reproduction

the event not firing when switching network quality

### System Info

```shell
System:
    OS: macOS 14.6.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 124.82 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.4.0 - /usr/local/bin/node
    Yarn: 1.22.22 - /usr/local/bin/yarn
    npm: 10.8.1 - /usr/local/bin/npm
    pnpm: 9.9.0 - /usr/local/bin/pnpm
    Watchman: 2024.09.23.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 130.0.6723.117
    Safari: 17.6
  npmPackages:
    livekit-client: ^2.1.3 => 2.1.3
```

### Severity

blocking all usage of LiveKit

**Comment by lukasIO** [comment]
this is expected when there's no track subscription active from the remote participant, see https://github.com/livekit/livekit/issues/2717
