### ISSUE TITLE
[feature request] api for adjust recording volume

### ISSUE THREAD

**Issue by showonne** [livekit/client-sdk-js#1312]
### Describe the problem

I found agora provide an api for adjust recording volume https://api-ref.agora.io/en/voice-sdk/electron/4.x/API/class_irtcengine.html#api_irtcengine_adjustrecordingsignalvolume , but livekit can only setVolume for RemoteParticipant. I'm not sure if it can be done with TrackProcessor, if can, should we encapsulate it to core or a official plugin. 

### Describe the proposed solution

Provide an api for it, let user can control recording volume in ControlBar

### Importance

nice to have

**Comment by davidzhao** [comment]
you can control volume with [setVolume](https://docs.livekit.io/client-sdk-js/classes/RemoteParticipant.html#setVolume)

**Comment by showonne** [comment]
> you can control volume with [setVolume](https://docs.livekit.io/client-sdk-js/classes/RemoteParticipant.html#setVolume)

This api only exist on RemoteParticipant, and my meaning is maybe add a API for LocalParticipant, the agora's api link I referenced also use to adjust the local recording volume.

**Comment by lukasIO** [comment]
by default `autoGainControl` is enabled on all local tracks. There's not dedicated API to set the volume for local tracks but you can still use `setVolume` on the receiving side for a user's tracks as davidzhao mentioned
