### ISSUE TITLE
No permissions received on ParticipantPermissionsChanged event

### ISSUE THREAD

**Issue by hoangtran98** [livekit/client-sdk-js#1314]
Hi team, 

I have the following code in the client.

```
localParticipant.addListener(ParticipantEvent.ParticipantPermissionsChanged, (permission) => {
      console.log("permission: ", permission) 
      // always undefined even though permission changed from backend
    }
  );
```

Backend logic:

```
lkapi = LiveKitAPI()

try:
         await lkapi.room.update_participant(UpdateParticipantRequest(
            room=ctx.room.name,
            identity=participant.identity,
            permission=ParticipantPermission(
                can_subscribe=True,
                can_publish=True,
                can_publish_data=True,
                can_update_metadata=True,
            ),
        ))
    finally:
        await lkapi.aclose()
```

I have upgraded all livekit client libraries to latest version and still have the issue of receiving no permission data when the participant permission is updated. Please help me with this.

Thanks

Hoang

### System Info

```shell
n/a
```

### Severity

blocking an upgrade

**Comment by lukasIO** [comment]
hey! 

This is expected, the argument received are the previous permissions, if there were none set explicitly, this might be empty. 
In your event handler check `participant.permissions` for the updated permissions
