### ISSUE TITLE
Remote participant video elements in Document PiP are wrongly detected as hidden

### ISSUE THREAD

**Issue by davideberlein** [livekit/client-sdk-js#1317]
### Describe the bug

We use the new Chrome Document Picture in Picture mode.
As soon as the remote participants video elements are displayed in the Document PiP window for a couple of seconds their video playback stops and I see a log message in the browser console that it was set to `visible: false` likely the visibility detection isn’t fully working in PiP windows.

### Reproduction

*Repro*
Start a LiveKit call adding the remote participants video elements to the dom.
Trigger [Document PiP](https://developer.mozilla.org/en-US/docs/Web/API/Document_Picture-in-Picture_API) and move the video elements into the PiP window.

*Expected*
Playback of the remote videos continues

*Actual*
Playbeck of the remote videos is paused after a couple of seconds. (The local participant's video playback continues)

### System Info

```shell
Google Chrome Version 130.0.6723.58 (Official Build) (arm64)
OSX
```

### Severity

blocking an upgrade

### Additional Information

I can propose a fix for this

**Comment by lukasIO** [comment]
hi @davideberlein 

thanks for the suggestion and the offer to propose a fix. 

This is where pip handling is currently done: https://github.com/livekit/client-sdk-js/blob/main/src/room/track/RemoteVideoTrack.ts#L349-L360
