### ISSUE TITLE
could not establish pc connection

### ISSUE THREAD

**Issue by hainanzhong2010** [livekit/client-sdk-js#1341]
### Describe the bug

when I click connet button after put livekiturl and token, the console show "could not establish pc connection
![Snipaste_2024-12-04_17-31-07](https://github.com/user-attachments/assets/11e18ccf-3652-4a71-8730-abb8c3e9464d)
"

### Reproduction

1、install livekit-server
docker run --rm -v /usr/local/docker/livekit:/output livekit/generate --local 
docker run -d -p 7880:7880 -p 7881:7881 -p 7882:7882/udp --name livekit-server -v /usr/local/docker/livekit/livekit.yaml:/livekit.yaml livekit/livekit-server --config /livekit.yaml --node-ip=127.0.0.1
2、run client-sdk-js demo
 pnpm install && pnpm examples:demo
3、connect
ws://localhost:7880
token:
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjkyMTE4ODMsImlzcyI6IkFQSWRrTmhMQW1IS3hLdSIsIm5hbWUiOiJUZXN0IFVzZXIiLCJuYmYiOjE3MzMyMTE4ODMsInN1YiI6InRlc3QtdXNlciIsInZpZGVvIjp7InJvb20iOiJteS1maXJzdC1yb29tIiwicm9vbUpvaW4iOnRydWV9fQ.b5ZzNqa_gIfA5lfTHEE9Ejgc3NHDQmlrOTBx2dUi1Ds

### System Info

```shell
chrome
```

### Severity

annoyance

**Comment by lukasIO** [comment]
this is likely a configuration issue, you can test your server setup with https://livekit.io/connection-test
