### ISSUE TITLE
RoomEvent.StateChanged event

### ISSUE THREAD

**Issue by lukasIO** [livekit/client-sdk-js#138]
In order to make it easier to subscribe to all roomstate changes it could be nice to expose this with a dedicated event.

```ts
room.on(RoomEvent.StateChanged, handleRoomStateChanged);
```

**Comment by davidzhao** [comment]
This makes a lot of sense. I've been thinking about how to simplify our events system. (the lack of types in the callbacks is something that bugs me a lot).

Perhaps it could be much more consistent, where we fire off events of different types and the user could choose which one they respond to.

**Comment by lukasIO** [comment]
True! I have an idea how to fix the lack of types without changing too much of the current codebase. Part of it would be to make use of https://github.com/andywer/typed-emitter

For the second part: do you mean as an example instead of `ParticpantEvent`s firing on the room and on the participant, to have (only) a central event hub for all events ?

**Comment by davidzhao** [comment]
> For the second part: do you mean as an example instead of `ParticpantEvent`s firing on the room and on the participant, to have (only) a central event hub for all events ?

yeah, was thinking we could fire a `ParticipantEvent.StateChanged` to notify the user of the update. the event object could contain a type field along with other objs. The events could also be subclassed to ensure correct typing.

**Comment by lukasIO** [comment]
I see. my initial proposal was supposed to be only about the room connection state. 
For example for a simple connection status indicator. 
Right now you need to listen to ' disconnected', 'reconnected', 'reconnecting' etc.. One event for connection state changes would simplify that.

Are you thinking that the `ParticipantEvent.StateChanged` would be an addition to the already existing events or is your idea that this single event would replace all others?

I have the feeling bundling everything into one event will lead to an api that would quickly become harder to work with and lead to less elegant code whenever someone wants to actually use the sdk.

**Comment by davidzhao** [comment]
I see what you mean. that makes sense and sgtm

**Comment by lukasIO** [comment]
closing with #143 merged
