### ISSUE TITLE
Enable Opus DTX to lower bandwidth during silience

### ISSUE THREAD

**Issue by davidzhao** [livekit/client-sdk-js#14]
https://datatracker.ietf.org/doc/html/rfc6716#page-13

By enabling DTX, we can achieve lower bandwidth requirements when tracks are near silent. This will enable us to support significantly larger simultaneous subscribed tracks.

**Comment by davidzhao** [comment]
jech suggested alternatively using audio level on SFU to determine when to skip audio packets to clients.

**Comment by boks1971** [comment]
Supporting DTX would be good as it allows codecs to output some comfort noise too. Another issue I have seen is with jitter buffers getting a bit out of whack when packet flow is interrupted. Worth exploring doing this on server side though.

We can also enabled DTX using SDP answer from server. I don't think it is required to do on client side. You can include `usedtx=1` in the `fmtp` for Opus (example of `fmtp` for Opus - `a=fmtp:111 minptime=10; useinbandfec=1`, just need to tack on `usedtx=1` in SDP answer from server). SDP reference: https://webrtchacks.com/sdp-anatomy/
