### ISSUE TITLE
Local peer metadata update feature

### ISSUE THREAD

**Issue by yogeshydvme** [livekit/client-sdk-js#148]
Can local SDK exposes way for users to update local peer metadata from client side itself, so that other users can get that metadata.

Any new participants should get metadata for all existing users. 

Why there is a dependency of updating it from Server side.

**Comment by davidzhao** [comment]
We don't support client-side updates to metadata currently. Participant and room metadata could contain permission/state information where the server is the authority of the data. For example, for a poker game, it could contain the player's state, such as the number of chips they currently have.

While it is more code to write having to interact with your server, I think it offers a lot more flexibility in enforcing the app's business logic
.

**Comment by yogeshydvme** [comment]
But then in that case for very simple operation like a user wants to do hand raise there is no way to use websocket connection to send this info to server where it can apply the participantUpdate and send notification to others, Do people have to always write web server running server side sdk and ServiceRoomClient to do that operation.

It seems to be overhead, where maybe local peer-update should be allowed from local client.

I see some ion-sfu projects where they talk to ws to send notification like peer-update to server only not to other participant, then server takes care of sending this peer-updated to other users. This doesn't have overhead of http and managing own server, but at the same time gives options to send a lot more events to ws server where it can take care of what to do to those messages.

**Comment by yogeshydvme** [comment]
I am new to webrtc open source, I love live kit btw. Sorry if I am not making sense.

**Comment by lukasIO** [comment]
to send data to other participants from your client, you can use the `publishData` API on the local participant.

in order to get the most recent state of all participants for a newly joined participant you could do something like 
```ts
room.on(RoomEvent.ParticipantJoined, (participant) => room.localParticipant.publishData(myCurrentState, DataPack_Kind.Reliable, [participant]);
```

**Comment by yogeshydvme** [comment]
But let's say we want to extend and introduce this behaviour where a local participant is able to update its own peer data that what will be changes we have to take care of like introducing certain event that can be sent using publishData and maybe intercepting it at server so that it can apply updateParticipant operation to send notification to all other user. 
It will be great help if you can point me to such required changes.

**Comment by davidzhao** [comment]
clients will not be able to update their own metadata under the current security model. since users are relying on this security model, it's not a trivial thing to add.

**Comment by lukasIO** [comment]
closing, as using the server-sdk is the correct approach to set participants' metadata and for everything else, there's the publish data APIs.
