### ISSUE TITLE
IOS safari doesn't connect to a room.

### ISSUE THREAD

**Issue by tsyrya** [livekit/client-sdk-js#174]
SDK verion: 0.17.1
LiveKit server version: 15.5
IOS version: 15.3

Only in IOS safari the client can't connect to a room. If the client connects without publishing any media stream then after some time the connection happens. But if there is at least one publishing media stream, then seems like the client can't finish the connection.

**Comment by davidzhao** [comment]
Are you able to reproduce with the [sample JS](https://github.com/livekit/client-sdk-js#sdk-sample) client?

**Comment by tsyrya** [comment]
@davidzhao Yeah, same behavior. The log window says "could not connect after timeout". 
![Screenshot from 2022-03-28 09-32-36](https://user-images.githubusercontent.com/8085730/160312533-8ca8f645-3d24-4eab-8447-5721071000bc.png)
![photo_2022-03-28_09-33-54](https://user-images.githubusercontent.com/8085730/160312555-59defab4-e05d-4d14-805e-486ecaa8abc8.jpg)

The first screenshot were taken from a PC, and the second from an iphone.

**Comment by davidzhao** [comment]
Ah I see the issue, you are loading the sample app over insecure HTTP. Mobile Safari does not allow media capture when it's running over an insecure connection.

Can you try going to https://example.livekit.io ?

**Comment by tsyrya** [comment]
![photo_2022-03-28_15-33-21](https://user-images.githubusercontent.com/8085730/160348814-c9185938-7548-49d3-b092-31288d70656a.jpg)

Unfortunately, it is still the same.  Also, the previous connection was working over HTTPS as well. Just out of curiosity, what made you think it was insecure?

**Comment by davidzhao** [comment]
Your initial screenshot shows Safari's address bar showing `Not secure`

**Comment by tsyrya** [comment]
Ahh, I am sorry, I was wrong. But anyway with the example.livekit.io it didn't work as well :(

**Comment by davidzhao** [comment]
interesting.. it's working well for me against our server. Can you share any debugging logs from mobile safari?  [here are instructions](https://www.lifewire.com/activate-the-debug-console-in-safari-445798) on how you could accomplish that.

**Comment by tsyrya** [comment]
```
[Log] connecting to – "wss://livekit.test.appercode.com/rtc?access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NDk1MTY0MzksImlzcyI6IkFQSTlrRjNnQkNoaXRxV…" (2.972e1033.chunk.js, line 2)
"wss://livekit.test.appercode.com/rtc?access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NDk1MTY0MzksImlzcyI6IkFQSTlrRjNnQkNoaXRxViIsImp0aSI6IlVzZXIgMSIsIm5iZiI6MTY0NjkyNDQzOSwic3ViIjoiVXNlciAxIiwidmlkZW8iOnsicm9vbSI6InJvb20xIiwicm9vbUpvaW4iOnRydWV9fQ.wJTg9gdoWYf8a9Orv6RRfDCl1QtcWGbr33l5Y0IkobM&sdk=js&version=0.17.1&protocol=6"
[Log] connected to Livekit Server version: 0.15.5, region:  (2.972e1033.chunk.js, line 2)
[Log] room event – "stateChanged" – "connected" (2.972e1033.chunk.js, line 2)
[Log] received server offer – "offer" – "stable" (2.972e1033.chunk.js, line 2)
[Log] sending answer (2.972e1033.chunk.js, line 2)
```

**Comment by tsyrya** [comment]
That's it,the UI shows the error ("could not connect after timeout"). Might it be because the timeout too small and somehow it takes more time in safari to establish the connection?

**Comment by frisbee-mks** [comment]
Having the same issue, but in every browser. It seems like some network issue for me. One of my coworkers also facing this issue(he is in other country, using other OS).
But v0.15.4 and below is working.
I have checked the differences and found that in `client-sdk-js` since `v0.15.4` in `RCTEngine.ts` file event handler `RTCPeerConnection.oniceconnectionstatechange` replaced with `RTCPeerConnection.onconnectionstatechange`.
The issue is gone when I replaced `onconnectionstatechange` with `oniceconnectionstatechange` on my local environment in the latest sdk version for testing purpose(and all `connectionState` checks with `iceConnectionState`).

Can you tell me why this event handlers have been changed after `v0.15.4`?

**Comment by davidzhao** [comment]
closing issue as it's stale. please file a new issue if problem persists.
