### ISSUE TITLE
Unable to use livekit client with http: protocol.

### ISSUE THREAD

**Issue by caiiiycuk** [livekit/client-sdk-js#188]
Hi, I unable to use livekit with http: protocol. I have site that serve both on https, and http. Everything works fine on https, but when I open it with http protocol livekit never connected. I don't need something special in case of http protcol I only need for data channels, so I don't want to use media devices. The problem is inside [livekit-client](https://github.com/livekit/client-sdk-js/blob/HEAD/src/room/Room.ts#L293)

```js
        if (isWeb()) {
          window.addEventListener('beforeunload', this.onBeforeUnload);
          navigator.mediaDevices.addEventListener('devicechange', this.handleDeviceChange); **// <-- HERE**
        }

        resolve(this);
```

With http protocol navigator.mediaDevices are not defined, so resolve is never called.

**Comment by lukasIO** [comment]
closed via [0220296](https://github.com/livekit/client-sdk-js/commit/02202961e195d02eb3b6e57729db3a8d45ad9b7b)
