### ISSUE TITLE
When I upgrade from 0.17.0 to 0.18.2, the project reports an error (node:v14.18.2,webpack，vue cli4 )，How to deal with it

### ISSUE THREAD

**Issue by fragransQ** [livekit/client-sdk-js#209]
./node_modules/livekit-client/dist/livekit-client.esm.js

Module parse failed: Unexpected token (4675:48)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|             creationTime: isSet$1(object.creationTime) ? Number(object.creationTime) : 0,
|             turnPassword: isSet$1(object.turnPassword) ? String(object.turnPassword) : '',
>             enabledCodecs: Array.isArray(object?.enabledCodecs)
|                 ? object.enabledCodecs.map((e) => Codec.fromJSON(e))
|                 : [],

 @ ./node_modules/cache-loader/dist/cjs.js??ref--13-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/meeting/index.vue?vue&type=script&lang=js& 88:0-64 234:96-101 241:20-32 401:22-31 401:88-97 401:160-169 401:216-225 401:276-285 575:13-22 575:78-87 575:149-158 575:204-213 575:263-272
 @ ./src/components/meeting/index.vue?vue&type=script&lang=js&
 @ ./src/components/meeting/index.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--13-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/meeting.vue?vue&type=script&lang=js&
 @ ./src/views/meeting.vue?vue&type=script&lang=js&
 @ ./src/views/meeting.vue

**Comment by lukasIO** [comment]
hi @fragransQ,
thanks for the report.
There seem to be issues around older webpack versions and its parser (acorn) with optional chaining, could you tell me the version of webpack you are using to confirm that this might be the issue?

**Comment by fragransQ** [comment]
> hi @fragransQ, thanks for the report. There seem to be issues around older webpack versions and its parser (acorn) with optional chaining, could you tell me the version of webpack you are using to confirm that this might be the issue you are seeing?  

"webpack": "^4.0.0",

**Comment by lukasIO** [comment]
@fragransQ thanks, upgrading to 0.18.3 should fix your issue!
