### ISSUE TITLE
Vue project  error Module parse failed: Unexpected token

### ISSUE THREAD

**Issue by gzh6473** [livekit/client-sdk-js#213]
In the following snippet, the inability to parse results in an exception, the error is Module parse failed: Unexpected token

`const opts = {
        ...options,
    };`

`const opts = {
            ...(_a = this.roomOptions) === null || _a === void 0 ? void 0 : _a.publishDefaults,
            ...options,
        };`

`this.options.audioCaptureDefaults = {
            ...audioDefaults,
            ...options === null || options === void 0 ? void 0 : options.audioCaptureDefaults,
        };
        this.options.videoCaptureDefaults = {
            ...videoDefaults,
            ...options === null || options === void 0 ? void 0 : options.videoCaptureDefaults,
        };
        this.options.publishDefaults = {
            ...publishDefaults,
            ...options === null || options === void 0 ? void 0 : options.publishDefaults,
        };`

**Comment by lukasIO** [comment]
hi @gzh6473,

could you share what version of vue you are using so that we can reproduce and find the right fix?

**Comment by lukasIO** [comment]
@gzh6473 could you try with version `0.18.4-RC5` and see if it fixes your issues?

**Comment by gzh6473** [comment]
> hi @gzh6473,
> 
> could you share what version of vue you are using so that we can reproduce and find the right fix?

2.5.2
