### ISSUE TITLE
Safari - "InvalidAccessError: Failed to set remote offer sdp: Failed to set remote video description send parameters."

### ISSUE THREAD

**Issue by leslie-heinzen** [livekit/client-sdk-js#25]
When on Safari, a user is unable to see remote participant video tracks that are sent via h264 simulcast from browsers that have the 42001f profile available. As you guys have noted in the server code, the `42001f` profile is unsupported in Safari: https://github.com/livekit/livekit-server/commit/4ce29799cfd4fc4e39d96b3dda62f1f547d3892f

However, the baseline codec seems to be making it through from Chrome participants, at least. This is from a `sendonly` offer sdp grabbed from some browser logs:

```
v=0
o=- 7320374909748723303 1628044518 IN IP4 0.0.0.0
s=-
t=0 0
a=fingerprint:sha-256 AB:7E:F5:C3:31:EF:AE:94:02:E0:1A:97:20:B2:89:FF:8B:D1:D1:A2:1B:4F:C4:03:C8:8B:09:D7:B4:79:FF:2D
a=group:BUNDLE 0 1
m=video 9 UDP/TLS/RTP/SAVPF 102
c=IN IP4 0.0.0.0
a=setup:actpass
a=mid:0
a=ice-ufrag:jbJTpnfaRAcgQTad
a=ice-pwd:QcTqYYWKZRUbiixrLkeUVMwugbKDSJBe
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:102 H264/90000
a=fmtp:102 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f
a=rtcp-fb:102 goog-remb
a=rtcp-fb:102 transport-cc
a=rtcp-fb:102 ccm fir
a=rtcp-fb:102 nack
a=rtcp-fb:102 nack pli
a=ssrc:464145329 cname:PA_TZk9wyEQB79u|TR_cZ7uqAwHHSXe
a=ssrc:464145329 msid:PA_TZk9wyEQB79u|TR_cZ7uqAwHHSXe TR_cZ7uqAwHHSXe
a=ssrc:464145329 mslabel:PA_TZk9wyEQB79u|TR_cZ7uqAwHHSXe
a=ssrc:464145329 label:TR_cZ7uqAwHHSXe
a=msid:PA_TZk9wyEQB79u|TR_cZ7uqAwHHSXe TR_cZ7uqAwHHSXe
a=sendonly
m=audio 9 UDP/TLS/RTP/SAVPF 111
c=IN IP4 0.0.0.0
a=setup:actpass
a=mid:1
a=ice-ufrag:jbJTpnfaRAcgQTad
a=ice-pwd:QcTqYYWKZRUbiixrLkeUVMwugbKDSJBe
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:111 opus/48000/2
a=fmtp:111 minptime=10;useinbandfec=1
a=rtcp-fb:111 transport-cc
a=ssrc:2246747591 cname:PA_TZk9wyEQB79u|TR_HQewpt7DVKad
a=ssrc:2246747591 msid:PA_TZk9wyEQB79u|TR_HQewpt7DVKad TR_HQewpt7DVKad
a=ssrc:2246747591 mslabel:PA_TZk9wyEQB79u|TR_HQewpt7DVKad
a=ssrc:2246747591 label:TR_HQewpt7DVKad
a=msid:PA_TZk9wyEQB79u|TR_HQewpt7DVKad TR_HQewpt7DVKad
a=sendonly
```

I think the issue is here: https://github.com/livekit/client-sdk-js/blob/b6a8b04f10984e7060b3af602cc605582821b7a1/src/room/participant/LocalParticipant.ts#L342

The codecs appear to be ordered in such a way that the first codec found will always be the baseline profile (42001f) if the browser has that codec. The `.find` might need to be a little more robust and also check that the `sdpFmtpLine` includes 42e01f if the videoCodec is `h264` (if the `sdpFmtpLine` property exists. I think it might only be in Chrome and possibly FF). Here is a lazy hack I experimented with and was able to get consistent cross-browser h264 simulcast behavior:

```ts
const selected = cap.codecs.find((c) => {
  const codec = c.mimeType.toLowerCase();
  const matchesVideoCodec = codec === `video/${videoCodec}`;

  videoCodec === "h264" && c.sdpFmtpLine
    ? matchesVideoCodec && c.sdpFmtpLine.includes("42e01f")
    : matchesVideoCodec || codec === "audio/opus";
});
```

**Comment by davidzhao** [comment]
@leslie-heinzen this is a great catch! 

Do you want to open a PR for it? we can get it merged soon. Would be great to format that function to be more readable. it seems to be packing quite a bit of logic in there.
