### ISSUE TITLE
P2P mesh 

### ISSUE THREAD

**Issue by no-1ne** [livekit/client-sdk-js#270]
Hello all, thanks for livekit
Have a feature request, can clients connect p2p as a mesh and sending data among themselves while TURN and recording going livekit SFU way with an extra connection to SFU. 

What do you think, can be energy efficient for attendees < 8 also saves outgoing bandwidth costs on SFU side. 

![Screenshot_20220617-044135528 (1)](https://user-images.githubusercontent.com/11027129/174193047-2e2bf20e-5e08-433c-93e3-f515f0408fa2.jpg)

https://element.io/blog/introducing-native-matrix-voip-with-element-call/

**Comment by davidzhao** [comment]
Hey @no-1ne, we do not have plans to support P2P mode.

In practice, it brings quite a bit of complexity to the system and makes is much harder to achieve high reliability. It also stresses users uplinks: upstream bandwidth constraints are very real. In real world applications, we've seen problems with P2P WebRTC in rooms with more than 3 participants.

**Comment by aehlke** [comment]
I'll just add that 3 participant realtime, or perhaps more if the data was not video (say, realtime comments in text), is still very useful. Having all user data go through servers is a big liability and privacy concern. I'll track this in lieu of that https://github.com/livekit/livekit/issues/303

**Comment by davidzhao** [comment]
You are absolutely right that you *can* get WebRTC to work well with mesh where it's only sending data / low-bitrate audio. In that case using plain WebRTC would be the path forward, you wouldn't need LiveKit there.

E2EE is pretty important in a SFU topology, we'll use https://github.com/livekit/livekit/issues/303 to keep track of that request.

**Comment by aehlke** [comment]
>In that case using plain WebRTC would be the path forward

Are you saying this is readily doable with plain WebRTC without a lib? Or that it's in as much a need of a lib and out of scope for LiveKit

**Comment by davidzhao** [comment]
It might be complex, but it's definitely possible to build it with WebRTC. The question is whether that complexity is handled by a library or within your own software.

And yes, this is out of scope for LiveKit.

**Comment by bekriebel** [comment]
I agree that LiveKit doesn't need the addition of p2p mesh. If you are looking for a good library to support that, I had good luck with  https://github.com/feross/simple-peer

Their library is easy to work with and very lightweight. However, I ultimately went with LiveKit because p2p mesh wasn't a good fit for my use case.

**Comment by aehlke** [comment]
>and having a P2P mesh optimisation within that blackbox called livekit

Can you elaborate what you mean by this?
