### ISSUE TITLE
track cannot be muted before/immediately after publishing

### ISSUE THREAD

**Issue by bekriebel** [livekit/client-sdk-js#28]
Steps to reproduce:
1. Create your tracks using `createLocalTracks`
2. Mute the audio track that you have created using `audioTrack.mute()`, leave the vide track unmuted
3. Connect to your livekit server using `connect()` and pass the existing tracks
4. Connect another client to the server - observe that audio is correctly not transmitting
5. Mute your video track using `videoTrack.mute()`
6. Your audio will start transmitting.

(This will also happen if immediately muting a track after the connect has succeeded).

I believe this is being caused by the fact that the mute state does not appear to be sent to the engine when initially adding a track. So, when the video track gets muted `LocalParticipant.updateInfo` is being called which includes: https://github.com/livekit/client-sdk-js/blob/63e0be4f48b6650f936568ab31b6da6162be3197/src/room/participant/LocalParticipant.ts#L222-L234 This unmutes the local track.

This can be tested with the sample code by adding the mute step to this part of the code:
https://github.com/livekit/client-sdk-js/blob/63e0be4f48b6650f936568ab31b6da6162be3197/example/sample.ts#L225-L229

Making it:
```js
    } else if (publication.kind === Track.Kind.Audio) {
      // skip adding local audio track, to avoid your own sound
      // only process local video tracks
      audioTrack = <LocalAudioTrack>publication.track;
      appendLog('muting audio');
      audioTrack.mute();
    }
```

I ran into this when working on an app that saves the user's mute state between sessions, so a track is immediately muted before/during connection if that is the state they last used.

Two requests/suggestions:
1. Reverse the logic of `LocalParticipant.updateInfo` to push the local state to the server instead of pulling local state from the server. I don't think the server mute state should ever override the local mute state of a track.
2. Push the mute state of a track to the server at the time it is added.

I can try to make a PR for this soon, but I'm still trying to figure out the best way to pass the mute state during the track add step.

**Comment by davidzhao** [comment]
good find. I think the core issue is mute status on the server has gotten out of sync with local state. it doesn't consider the case where you'd publish a track muted to start. I think to solve this properly, we would want to change the protocol so that you can add a muted track when publishing it.

a workaround for now would be to publish the track, then mute it right when the future returned by `publishTrack` resolves.

we'll look at fixing the root cause in the next release.

**Comment by bekriebel** [comment]
Hrmm... I just checked server side logs and realized that when I call `mute` immediately after an await on `connect`, I get this warning: 
```json
{"level":"warn","ts":1628631941.3027077,"caller":"rtc/participant.go:541","msg":"could not locate track","track":"TR_uzC8GiAjdXRm"}
```
It looks like that promise gets returned before the server has actually populated `publishedTracks` here: https://github.com/livekit/livekit-server/blob/896b28d45db1bb71b6351eec2323984c7b345d27/pkg/rtc/participant.go#L540

**Comment by bekriebel** [comment]
I think I've dug into this as far as I can for now. This is the full livekit-server logging when running:
```js
await liveKitRoom.localParticipant.publishTrack(audioTrack);
audioTrack.mute();
```

```json
{"level":"debug","ts":1628638269.8149612,"logger":"livekit","caller":"service/roommanager.go:430","msg":"add track request","participant":"bekit","pID":"PA_QLTPSccEhGHn","track":"4677e6c2-73f6-4ebf-b8d7-e97a6a458e45"}
{"level":"info","ts":1628638269.8962603,"logger":"livekit","caller":"rtc/participant.go:543","msg":"could not locate track","track":"TR_M5BVMkGhVJBd"}
{"level":"debug","ts":1628638269.9124758,"logger":"livekit","caller":"rtc/participant.go:250","msg":"answering pub offer","state":"ACTIVE","participant":"bekit","pID":"PA_QLTPSccEhGHn"}
{"level":"debug","ts":1628638269.9134264,"logger":"livekit","caller":"rtc/participant.go:270","msg":"sending answer to client","participant":"bekit","pID":"PA_QLTPSccEhGHn"}
{"level":"debug","ts":1628638270.016489,"logger":"livekit","caller":"rtc/participant.go:709","msg":"mediaTrack added","participant":"bekit","pID":"PA_QLTPSccEhGHn","track":"4677e6c2-73f6-4ebf-b8d7-e97a6a458e45","rid":""}
{"level":"debug","ts":1628638270.0244777,"logger":"livekit","caller":"rtc/mediatrack.go:308","msg":"NewBuffer","MaxBitRate":3145728}
```

Near as I can tell, the server returns with a message that the track was published before it actually has been and locks get released, so when `mute()` is called, the request gets in before the server publication list is updated and it fails. I think that should probably be a different issue, though I don't know if it should go under here or `livekit-server`.

For now, I've pushed a PR that at least doesn't let the server state override the local client state. I'll also add a temporary `sleep` into my code after a connection is established, though I'd much rather have a valid callback to key off of and for the track to acquire the mute status at time of adding.

**Comment by davidzhao** [comment]
Hey @bekriebel I have a server-side PR that should resolve this. Give the above branch a try and see if it works for you.

We'll still need to update clients to ensure that if a track is already muted, its status will be respected.

**Comment by bekriebel** [comment]
Thanks! Just tested a server build with that branch and it seems to have fixed the "mute immediately after connect" issue.
