### ISSUE TITLE
TypeScript: `createLocal…Track`  should accept type `MediaTrackConstraints`

### ISSUE THREAD

**Issue by Philzen** [livekit/client-sdk-js#284]
I am using `createLocalVideoTrack()` and would like to supply an `aspectRatio` and `ideal` dimension, but not a fixed `width`/`height`, which the current interface unfortunately mandates.

As the options given to `createLocalVideoTrack` and `createLocalAudioTrack` are merged in `constraintsForOptions()` into an object containing `MediaTrackConstraints` as per the [W3C spec](https://w3c.github.io/mediacapture-main/#media-track-constraints) anyway, wouldn't it be feasible to have the same uniform interface in the first place here?

**Comment by lukasIO** [comment]
we'll keep this in mind for a major version change, until then closing as not planned
