### ISSUE TITLE
Issue with Track.restartTrack on Samsung devices

### ISSUE THREAD

**Issue by davidzhao** [livekit/client-sdk-js#312]
A user has reported Track.restartTrack on certain Samsung devices would fail consistently. Of the devices tested, the following fails:
* S10
* S21
* S22

Track.sender gets set to undefined; seemingly related to when mediaStreamTrack.stop() is called. The user reported doing so also kills the PeerConnection

**Comment by lukasIO** [comment]
`track.sender` was being set to `undefined` in `track.stop` calls. 

fixed in #325
