### ISSUE TITLE
Reconnect fails if server is forcefully killed and started again

### ISSUE THREAD

**Issue by taskbit** [livekit/client-sdk-js#313]
I'm simulating a scenario where a local livekit node is forcefully killed and started again.

1. Start livekit-server (default config) (1.1.1)
2. Open 2 browsers with the livekit-client-sdk-js/example app (1.2.0)
3. Connect both clients
4. Forcefully kill the livekit-server process
5. Start livekit-server

**Expected**: Clients would be able reconnect and resume streaming automatically.
**Current**: Clients are in the disconnected state

Note: Quickly starting the server again (before the 2nd reconnect attempt in livekit-client-sdk) results in the expected state.
If I wait a bit and start the server after about 10 seconds the clients are in the disconnected state and won't reconnect.

Logs

[Client 1](https://gist.github.com/taskbit/4229c0b7be22f20d58212d0dc61b8dfa)
[Client 2](https://gist.github.com/taskbit/b74abbd67ab75880e17bd718da56a073)
[Server](https://gist.github.com/taskbit/50a47b214567eab8a1fba25aca374eb1)

**Comment by davidzhao** [comment]
I'm not able reproduce this either. I believe this issue has been fixed. Feel free to reopen if it persists for you.
