### ISSUE TITLE
Signal reconnect logic disconnects the room

### ISSUE THREAD

**Issue by bekriebel** [livekit/client-sdk-js#32]
When the websocket connection gets disconnected and the reconnect logic is triggered, the engine also triggers a disconnect. So, even when the reconnection succeeds, the engine & room get disconnected.

This appears to be coming from here: https://github.com/livekit/client-sdk-js/blob/2e29ad9badd004f140ba0c9dc1f6c666313daef4/src/room/RTCEngine.ts#L264-L267

Which is coming from here: https://github.com/livekit/client-sdk-js/blob/2e29ad9badd004f140ba0c9dc1f6c666313daef4/src/api/SignalClient.ts#L321-L324

I stopped tracing back at this point to see where the root cause is, but it looks like a lot of this logic was added in this commit: https://github.com/livekit/client-sdk-js/commit/7cdc80be47197beff8d73e7d33fe7ca04530e9e6.

I had this happen in a real setup when there was a network interuption, but I think a clean way to test it manually is to call `room.engine.client.ws.close()`

**Comment by davidzhao** [comment]
hey @bekriebel, this is actually a limitation on LiveKit server when running without Redis. I'll file a bug under livekit-server. Try running it with Redis and it should reconnect for you.

FYI, the leave message is sent by the server when it needs to remove a participant from the room. It also gets sent when server couldn't reconnect the client to the room, which happens in non-redis mode.

**Comment by davidzhao** [comment]
Server issue that is the root cause: https://github.com/livekit/livekit-server/issues/83
