### ISSUE TITLE
Video Mute/Unmute event is not working 

### ISSUE THREAD

**Issue by ShubhamJuIT** [livekit/client-sdk-js#33]
When mute/unmute my video, event for same doesn't gets called.

This only happening with video, for audio mute/unmute event is triggered properly.

I am using the latest version of livekit-client 1.11.1

---- Mute ----
(pub as LocalTrackPublication).mute();

----- UNmute ----
videoPub.forEach(pub => {
                (pub as LocalTrackPublication).unmute();
            });
            
This is how am an doing the mute unmute

**Comment by davidzhao** [comment]
which server version are you running? are there any logs in the client side? (you can turn on logging by [setting logLevel](https://docs.livekit.io/client-sdk-js/interfaces/connectoptions.html#loglevel) during connect)

**Comment by ShubhamJuIT** [comment]
Server Version previously i was using v0.12.0, right now I tried with latest version present in docker hub (livekit/livekit-server:v0.12) 

The logs that I have provided is with v0.12


**When mute/Unmute Video**
### Client Side
restarting track with constraints {width: {…}, height: {…}, frameRate: {…}}
instrument.js:110 re-acquired MediaStreamTrack

### Server Side (No Log coming after video mute/unmute)


**Log when mute/unmute audio**
### Client Side
Shubham Kumar - onMuted
instrument.js:110 Shubham Kumar - onMuted
instrument.js:110 Shubham Kumar - onMuted
### Server Side
2021-08-17T02:25:19.295Z	DEBUG	livekit	rtc/participant.go:563	mute status changed	{"participant": "Shubham Kumar", "pID": "PA_Umcsr9XEJnAH", "track": "TR_Ai3SUdsHbGL3", "muted": true}
2021-08-17T02:25:22.059Z	DEBUG	livekit	rtc/participant.go:563	mute status changed	{"participant": "Shubham Kumar", "pID": "PA_Umcsr9XEJnAH", "track": "TR_Ai3SUdsHbGL3", "muted": false}
2021-08-17T02:25:23.652Z	DEBUG	livekit	rtc/participant.go:563	mute status changed	{"participant": "Shubham Kumar", "pID": "PA_Umcsr9XEJnAH", "track": "TR_Ai3SUdsHbGL3", "muted": true}

**Comment by davidzhao** [comment]
@ShubhamJuIT Which browser are you using? 

I'm unable to reproduce this using our JS sample app or React example app. Can you try to see if you could get a repro with the JS sample app?  run `yarn sample`

**Comment by ShubhamJuIT** [comment]
Its also happening in JS sample app if we make video as false when connect

room = await connect(url, token, {
      logLevel: LogLevel.debug,
      audio: true,
      video: false,
      // video: {
      //   resolution: VideoPresets.qhd.resolution,
      // },
      simulcast,
    });

**Comment by davidzhao** [comment]
If you've disabled video.. there are no tracks published.. therefore mute wouldn't do anything.

**Comment by ShubhamJuIT** [comment]
Yes got it.

but what i have to do is initially I will disable the video, then when user clicks on enable video button, it will then publish the video track. Event of this track is not receiving.

I am using this to publish the track
`room.localParticipant.publishTrack(audioTrack)`

And for this publish event for mute unmute is not coming

**Comment by davidzhao** [comment]
I'm not sure what you mean, publish will not trigger an unmute.. are you trying to mute/unmute immediately after publishing? can you paste the full snippet?

**Comment by ShubhamJuIT** [comment]
by default my video is disabled, once user click on video button, I am publishing the track and this track is also be received by remote participants.  For mute/unmute icon in UI I am depended on the event but in this case I am not getting the event for mute/unmute, so I am not able to properly show mute/unmute icon

**Comment by ShubhamJuIT** [comment]
@davidzhao Have you seen the shared snippet

**Comment by davidzhao** [comment]
yes I have.. I'm not sure if I understand the issue.

`For mute/unmute icon in UI I am depended on the event`

which event are you dependent on? when you publish the track for the first time, remote participants will receive TrackPublished & TrackSubscribed. Then when you mute/unmute, it'll receive muted/unmuted. Is it just listening to different events in addition?

**Comment by ShubhamJuIT** [comment]
I am depending on muted/unmuted event.

**Comment by davidzhao** [comment]
glad to hear it!
