### ISSUE TITLE
Room.setAndEmitConnectionState rejects a promise with Error: "disconnected from Room"  that cannot be handled

### ISSUE THREAD

**Issue by aravindanve** [livekit/client-sdk-js#356]
## Summary

The method `Room.setAndEmitConnectionState` rejects a promise with Error: "disconnected from Room" that cannot be handled, at least in the following scenarios, and possibly more:

1. Reconnection fails and max attempts are exhausted
2. When the room is in reconnecting state and I call disconnect

https://github.com/livekit/client-sdk-js/blob/9c999845a34984a24dc4b3b27a0c09746e2ba3c8/src/room/Room.ts#L1052-L1056

<img width="1676" alt="Screenshot 2022-07-24 at 11 52 03 AM" src="https://user-images.githubusercontent.com/5883448/180635362-879995db-7131-4453-a6d3-730c9dcb3e40.png">

#### 1. Reconnection failed and max attempts exhausted

It would be nice to be able to handle this gracefully. For now I'm using a Custom reconnect policy:

```js
import { DefaultReconnectPolicy } from "livekit-client";

export class CustomReconnectPolicy extends DefaultReconnectPolicy {
  constructor({ handleGiveUp }) {
    this.handleGiveUp = handleGiveUp;
  }

  nextRetryDelayInMs(context) {
    const result = super.nextRetryDelayInMs(context);
    if (result !== null) {
      return result;
    } else {
      return this.handleGiveUp(context);
    }
  }
}

```

But that results in the following problem

#### 2. When the room is in reconnecting state and I call disconnect

I handle reconnection failure by directing the user away from the conference page in my `CustomReconnectPolicy.handleGiveUp` callback. But during clean up, when I call `room.disconnect().catch(console.error)`, `Room.setAndEmitConnectionState` rejects the `connectFuture` that results in an unhandled rejection.

https://github.com/livekit/client-sdk-js/blob/9c999845a34984a24dc4b3b27a0c09746e2ba3c8/src/room/Room.ts#L1052-L1056

## Solutions

Do not reject a promise that is not returned or is inaccessible via the public API.

#### 1. Reconnection failed and max attempts exhausted

Additionally, emit the reason for disconnect here https://github.com/livekit/client-sdk-js/blob/9c999845a34984a24dc4b3b27a0c09746e2ba3c8/src/room/RTCEngine.ts#L469

#### 2. When the room is in reconnecting state and I call disconnect

disconnect() should only reject a promise that was returned during a call to connect() and not reject a promise that was created on reconnection.
https://github.com/livekit/client-sdk-js/blob/9c999845a34984a24dc4b3b27a0c09746e2ba3c8/src/room/Room.ts#L1040-L1044

**Comment by aravindanve** [comment]
Meanwhile, here's a hack to handle the error until the issue is resolved.

```js
const onConnectionStateChanged = (state) => {
  if (state === ConnectionState.Reconnecting) {
    // HACK: catch rejections on newly created connectFuture to
    // suppress unhandled rejection error
    if (room?.connectFuture && !room.connectFuture.promise._handled) {
      room.connectFuture.promise._handled = true;
      room?.connectFuture?.promise.catch(console.warn);
    }
    //
  } else if (state === ConnectionState.Disconnected) {
    // cleanup and exit room
    // ...
  }
};

room.on(RoomEvent.ConnectionStateChanged, onConnectionStateChanged);
```

**Comment by lukasIO** [comment]
Hi @aravindanve,

thanks for the detailed report, that makes it really easy to follow along!
Those are good calls.
We'll split this into two parts, one PR making sure that we don't reject a promise triggered (only) by reconnection logic.
And a second one emitting the disconnect reason when reconnect attempts are exhausted (this also requires an addition to the protocol)

**Comment by aravindanve** [comment]
@lukasIO thats great!

Since creating this issue, I came across more instances of unhandled rejections. There are a few scenarios I'm not able to reproduce at the moment, but I'll try and dig deeper when I encounter them again. But here is one more I think:

https://github.com/livekit/client-sdk-js/blob/c4bbec1081d4cb4c929e5c19e61204b471b62b02/src/room/Room.ts#L288-L295

On `connect()` when there is an error establishing signal connection, the `err` is caught, `Room.setAndEmitConnectionState` is called, which calls `reject()` on connectFuture. But connectFuture is never returned by the `connect()` function, instead the `err` caught in *L288* is rethrown. So it's impossible to handle the promise rejection "could not establish signal connection"

I think this problem will persist despite #359

**Comment by lukasIO** [comment]
thanks for pointing that out! 
Could you try it with the latest changes in #359 and see if that fixes all the issues you were seeing on your side?

**Comment by lukasIO** [comment]
Fixes are released in 1.2.5, if you get a chance it would be great to hear if those things are fixed for you.
Feel free to re-open the issue if not!

**Comment by aravindanve** [comment]
@lukasIO sure thing. I was just looking at the PR. I'll try it and let you know.

**Comment by aravindanve** [comment]
@lukasIO I haven't been able to go through all the changes yet, but here is one issue I found. The promise gets caught correctly, but it also throws an unhandled rejection because I suspect when `.finally()` is called, it creates another promise that is left unhandled.

https://user-images.githubusercontent.com/5883448/181797513-4b699856-232b-406e-aca1-797e3b10512b.mov

**Comment by aravindanve** [comment]
I was curious about something else. I see that there is no return statement after `reject(...` here:

https://github.com/livekit/client-sdk-js/blob/254283daf87a90bde38a07acf8fe62db7836ad6e/src/room/Room.ts#L302-L306

Is it intentional? Because the code continues to run, and the following timeout is set and never cleared as the connection is neither successful nor aborted:

https://github.com/livekit/client-sdk-js/blob/254283daf87a90bde38a07acf8fe62db7836ad6e/src/room/Room.ts#L309-L314

I think if this timeout is not cleared, it could fire after 15s even if the connection has been established with another successful call to `connect()`

**Comment by lukasIO** [comment]
@aravindanve great catches on both of the things!
Both oversights on my side, thanks for tracking them down!

**Comment by lukasIO** [comment]
If you'd want to fix these kind of issues, after tracking them down already, contributions are always welcome btw!

**Comment by lukasIO** [comment]
https://github.com/livekit/client-sdk-js/pull/368

**Comment by aravindanve** [comment]
Haha yes I considered it, but decided against doing so. I'm not entirely familiar with the livekit client-server protocol yet - didn't want to mess anything up. I started using livekit a little over a week ago. Once I have a little more experience with livekit, I'll try and contribute for sure!

**Comment by aravindanve** [comment]
@lukasIO #368 appears to fix both the issues above! I'll let you know if I find any other issues.

**Comment by lukasIO** [comment]
great, thank you for checking!
