### ISSUE TITLE
Support for Screen Sharing audio

### ISSUE THREAD

**Issue by saintplay** [livekit/client-sdk-js#36]
Hello! Congrats for this awesome project, I've been trying several open source solutions for WebRTC, but LiveKit really stands out for its simplicity and flexibility. Documentation, is great too.

It would be great to support audio when requesting a screen sharing stream.

I don't know if this is better suitable as an option or as default.

```
window.navigator.mediaDecies({ audio: true, video: true })
```

Because to receive an audio track the user needs the explicitly check the "share audio" anyway.

Regards

**Comment by davidzhao** [comment]
hi @saintplay, we should add support for audio as some browsers do support it. Unfortunately, this will change the API slightly since the current API would return only a LocalVideoTrack.

**Comment by saintplay** [comment]
What about createLocalScreenTracks? 

In plural, similar to createLocalTracks for getUserMedia?
