### ISSUE TITLE
I look for a Open source video conferencing application powered by LikeKit, something like Jitsi

### ISSUE THREAD

**Issue by stephane-klein** [livekit/client-sdk-js#362]
Hi,

I don't know where to post my question: do you know an open source video conferencing application powered on LiveKit, like [Jitsi](https://en.m.wikipedia.org/wiki/Jitsi)?

My goal: replace Jitsi by, maybe a better vidéo conferencing application.

Best regards,
Stéphane

**Comment by lukasIO** [comment]
Hi!
you can either try our (rather minimalistic) example app in https://github.com/livekit/livekit-react or ask the livekit community on slack https://livekit.io/join-slack, some people there might have built open source conferencing apps on top of livekit!

**Comment by boks1971** [comment]
This one is built using LiveKit - https://www.plugnmeet.org/
