### ISSUE TITLE
Quickly muting and unmuting audio causes a muting loop

### ISSUE THREAD

**Issue by bekriebel** [livekit/client-sdk-js#38]
If you quickly toggle the mute state of an audio track, the track goes into a state of muting and unmuting until disconnecting from the server. I'm not sure if this issue is in the client or server code.

Reproduction steps with the sample client:
1. Using the example/sample, add a set of hooks to log mute and unmute room events
```ts
    .on(RoomEvent.TrackMuted, () => appendLog("Track muted"))
    .on(RoomEvent.TrackUnmuted, () => appendLog("Track unmuted"))
```
2. Launch the sample and connect two clients.
3. Open the console on a client and quickly mute and unmute the audio track.
```ts
window.muteAudio(); window.muteAudio();
```
4. Observe from the second client that the audio track continues to get muted and unmuted.

The console command is the most reliable way to trigger it, but I have had it trigger in a real scenario with a push-to-talk setup where the user presses and immediately releases or accidentally double taps the push-to-talk key. This can be mitigated by adding a delay between mute calls in a client implementation, but it seems like something is getting into a bad state when a mute/unmute call are done back to back.

**Comment by bekriebel** [comment]
The problem is actually a bit worse than I originally thought. The timing seems to be based on the latency to the signaling server. If I test with a server located in far region, I'm able to get the issue to occur even with a 400ms debounce.

If I connect two clients, I can see that the time between the muting client seeing a local participant `TrackEvent Muted` and the remote client seeing the remote participant `trackMuted` event is over 500ms. If I call `mute()` and `unmute()` of a track within that timeframe, the issue occurs.

I'd rather not debounce my calls with that much time, since that could cause a lot of audio clipping. However, 500ms is easily within range of a user hitting and releasing a PTT button, so the problem is easy to trigger on distant servers.

**Comment by davidzhao** [comment]
this is not good.. I'll investigate today. I agree though it should handle latency and not trigger this callback loop.

**Comment by bekriebel** [comment]
@davidzhao I think I tracked it down to the `updateInfo` method in LocalParticipant.ts. The loops seems to happen with it matching the track mute status to the server. For kicks, I put in the previous patch that I made around this function and it seems to resolve this issue as well: #29.
