### ISSUE TITLE
Camera and microphone are getting enabled by itself

### ISSUE THREAD

**Issue by karthikSirsikar** [livekit/client-sdk-js#383]
This issue happens on mobile browsers.

Steps to reproduce:

1. Join the room with camera and microphone enabled
2. Disable camera and microphone
3. Switch to different app or go to home screen
4. Open the browser again

**Comment by lukasIO** [comment]
hi @karthikSirsikar,

thank you for the report, I could reproduce the bug and proposed a fix!
