### ISSUE TITLE
[Question] Filter out noise from video calls with client-sdk-js

### ISSUE THREAD

**Issue by loilukojk** [livekit/client-sdk-js#39]
Hi,
I am using client-sdk-js to create a complete client app. In my plan, I need feature of filter out noise from video calls but I can't find it in client-sdk-js. Do you have that feature? If not, have you put it in your roadmap?
Thanks!

**Comment by davidzhao** [comment]
can you try turning on noiseSuppression when creating the audio tracks? See https://docs.livekit.io/client-sdk-js/modules.html#createlocalaudiotrack

https://docs.livekit.io/client-sdk-js/interfaces/createaudiotrackoptions.html#noisesuppression

**Comment by loilukojk** [comment]
Now I'm adding some options for createLocalAudioTrack method but I have no idea what's it mean and how that params work between client and livekit server. Can you explain more about it?

My example code below:
const audioTrack = await createLocalAudioTrack({
    echoCancellation: true,
    noiseSuppression: {
      ideal: true,
    }
  })
const audioPublication = await room.localParticipant.publishTrack(audioTrack)

**Comment by davidzhao** [comment]
These are webrtc settings that LiveKit would pass through. For more see: https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints/noiseSuppression

setting them simply as `true` will suffice
