### ISSUE TITLE
Make DeviceManager export available in livekit-client

### ISSUE THREAD

**Issue by dwrtz** [livekit/client-sdk-js#394]
https://github.com/livekit/client-sdk-js/blob/fc97dd13f390ceb8d0da4ed398a54f6f400f1efd/src/room/DeviceManager.ts#L6

This is a useful class but I can't import it from livekit-client

**Comment by lukasIO** [comment]
hi @dwrtz,
the SDK exposes `Room.getLocalDevices` as a static method, which calls into the DeviceManager class. 
If you need broader access to the class, could you elaborate on the use case or what specific functionality you would like to see exposed?

**Comment by dwrtz** [comment]
Ah, that worked. I'm new to static methods.

Thanks!
