### ISSUE TITLE
OperationError: Failed to execute 'setLocalDescription' on 'RTCPeerConnection': Failed to set local offer sdp: Failed to set local video description recv parameters for m-section with mid='0'

### ISSUE THREAD

**Issue by Bloomingg** [livekit/client-sdk-js#399]
When i try to connet,get this error...  then  i can't publish my video or audio,but i can get other Track subscribed.
`OperationError: Failed to execute 'setLocalDescription' on 'RTCPeerConnection': Failed to set local offer sdp: Failed to set local video description recv parameters for m-section with mid='0'`

And i can publish success with h5.this error happened only on uniapp android.

After that,i try to use pure webrtc (navigator.mediaDevices.getUserMedia),i can publish and subscribed track successful.

**Comment by lukasIO** [comment]
hi @Bloomingg,
can you provide some details on your setup? I'm not familiar with uniapp.
Device/OS, Browser, Browser version?

Also, does the error still appear with the latest client version v1.2.11 ?

**Comment by Bloomingg** [comment]
> hi @Bloomingg, can you provide some details on your setup? I'm not familiar with uniapp. Device/OS, Browser, Browser version?
> 
> Also, does the error still appear with the latest client version v1.2.11 ?


OK, I will list the SDK and environment I use below:
livekit-client@1.2.10
hbuildx 3.4.14

**Comment by lukasIO** [comment]
thank you, can you try with livekit-client v1.2.11? We fixed some things in that version that might be related to what you are seeing!

**Comment by Bloomingg** [comment]
> thank you, can you try with livekit-client v1.2.11? We fixed some things in that version that might be related to what you are seeing!

sadly,i get failed agin...

**Comment by lukasIO** [comment]
Hoping that https://github.com/livekit/client-sdk-js/pull/400 would fix the issue for you. Could you try with the main branch of this repo? (changes haven't been published to npm yet)

**Comment by Bloomingg** [comment]
> Hoping that #400 would fix the issue for you. Could you try with the main branch of this repo? (changes haven't been published to npm yet)

Thank you!  I tried to do what you said, but I got an error again...
`18:17:34.940 Uncaught (in promise) OperationError: Failed to execute 'setLocalDescription' on 'RTCPeerConnection': Session error code: ERROR_CONTENT. Session error description: Failed to set local video description recv parameters for m-section with mid='1'..`

**Comment by lukasIO** [comment]
hm, would be great if you could turn on debug logs (`setLogLevel('debug')`) and post the entire logs for the failed connection sequence!

**Comment by Bloomingg** [comment]
> hm, would be great if you could turn on debug logs (`setLogLevel('debug')`) and post the entire logs for the failed connection sequence!

These are some logs I collected, but some objects cannot be printed. I'm not sure if this can help you
`18:46:12.038 connected to Livekit Server version: 1.1.2, region:  at app-view.js:23270
18:46:12.061 room event [object Object] at app-view.js:24215
18:46:12.085 received server offer [object Object] at app-view.js:22798
18:46:12.106 sending answer at app-view.js:21029
18:46:12.127 primary PC state changed [object Object] at app-view.js:22709
18:46:13.315 primary PC state changed [object Object] at app-view.js:22709
18:46:13.339 updating track subscription permissions [object Object] at app-view.js:16330
18:46:13.364 room event [object Object] at app-view.js:24215
18:46:13.408 on data channel 1, _reliable at app-view.js:22367
18:46:13.428 on data channel 3, _lossy at app-view.js:22367
18:46:13.894 using video encoding [object Object] at app-view.js:15625
18:46:13.918 scalabilityMode undefined at app-view.js:15629
18:46:13.941 received trackPublishedResponse [object Object] at app-view.js:22809
18:46:13.964 publishing audio with encodings [object Object] at app-view.js:16943
18:46:13.988 room event [object Object] at app-view.js:24215
18:46:14.012 received trackPublishedResponse [object Object] at app-view.js:22809
18:46:14.037 publishing video with encodings [object Object] at app-view.js:16943
18:46:14.061 get capabilities {"codecs":[{"clockRate":90000,"mimeType":"video/VP8"},{"clockRate":90000,"mimeType":"video/rtx"},{"clockRate":90000,"mimeType":"video/VP9","sdpFmtpLine":"profile-id=0"},{"clockRate":90000,"mimeType":"video/H264","sdpFmtpLine":"level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f"},{"clockRate":90000,"mimeType":"video/red"},{"clockRate":90000,"mimeType":"video/ulpfec"}],"headerExtensions":[{"direction":"sendrecv","uri":"urn:ietf:params:rtp-hdrext:toffset"},{"direction":"sendrecv","uri":"http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time"},{"direction":"sendrecv","uri":"urn:3gpp:video-orientation"},{"direction":"sendrecv","uri":"http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01"},{"direction":"sendrecv","uri":"http://www.webrtc.org/experiments/rtp-hdrext/playout-delay"},{"direction":"sendrecv","uri":"http://www.webrtc.org/experiments/rtp-hdrext/video-content-type"},{"direction":"sendrecv","uri":"http://www.webrtc.org/experiments/rtp-hdrext/video-timing"},{"direction":"sendrecv","uri":"http://www.webrtc.org/experiments/rtp-hdrext/color-space"},{"direction":"sendrecv","uri":"urn:ietf:params:rtp-hdrext:sdes:mid"},{"direction":"sendrecv","uri":"urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id"},{"direction":"sendrecv","uri":"urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id"}]} at app-view.js:17280
18:46:14.085 room event [object Object] at app-view.js:24215
18:46:14.105 starting to negotiate at app-view.js:22179
18:46:14.128 not able to set desired local description, falling back to unmodified offer {"error":"{\"stack\":\"Error: Failed to execute 'setLocalDescription' on 'RTCPeerConnection': Failed to set local offer sdp: Failed to set local video description recv parameters for m-section with mid='1'.\"}"} at app-view.js:22235
18:46:14.152 Uncaught (in promise) OperationError: Failed to execute 'setLocalDescription' on 'RTCPeerConnection': Session error code: ERROR_CONTENT. Session error description: Failed to set local video description recv parameters for m-section with mid='1'.. at app-view.js:1369
18:46:14.176 silence detected on local audio track at app-view.js:14083
18:46:15.777 room event [object Object] at app-view.js:24215`

**Comment by lukasIO** [comment]
thank you for the logs!
still not sure how to reproduce this unfortunately. 
we did some more compatibility related work for v1.3.0, you could give that a try!

**Comment by Bloomingg** [comment]
> thank you for the logs! still not sure how to reproduce this unfortunately. we did some more compatibility related work for v1.3.0, you could give that a try!


Thank you! I can connect and stream normally with the latest version!
