### ISSUE TITLE
Unhandled Error: could not establish publisher connection, state connected

### ISSUE THREAD

**Issue by merazgasalim** [livekit/client-sdk-js#435]
### Describe the bug

I'm receiving this bug from some of my web app users and I'm confused because I can't reproduce it at my end.

### Reproduction

I don't know how to reproduce it because this bug is captured from the devices of my web app users.

### Logs

```shell
Error
could not establish publisher connection, state connected

./node_modules/livekit-client/dist/livekit-client.esm.mjs in finish at line 22575:11
throw new ConnectionError("could not establish publisher connection, state ".concat((_b = this.publisher) === null || _b === void 0 ? vo {snip}

./node_modules/livekit-client/dist/livekit-client.esm.mjs in dest at line 22531:43
const msg = DataPacket.encode(packet).finish(); // make sure we do have a data connection

./node_modules/livekit-client/dist/livekit-client.esm.mjs in async Rs.publishData at line 20071:28
destinationSids: dest
```

### System Info

```shell
I got this error from the following systems

1-
Chrome 81.0.4044
SM-T560
Android 4.4.4

2-
Chrome Mobile 105.0.0
Samsung SM-A305F
Android 11

3-
Chrome 104.0.0
Windows 10
```

### Severity

serious, but I can work around it

### Additional Information

I'm not sure, but I think it's related to Mic Permissions because I found this console log on one of the affected devices

audioinputErr NotAllowedError: Permission denied
{
arguments: [
audioinputErr, 
{
message: Permission denied, 
name: NotAllowedError, 
stack: [undefined]
}
], 
logger: console
}

**Comment by davidzhao** [comment]
this error means you are trying to acquire mic/camera permissions while running on an insecure site. See [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia) for additional details.
