### ISSUE TITLE
Set participant volume for screenshare audio

### ISSUE THREAD

**Issue by lukasIO** [livekit/client-sdk-js#442]
### Describe the problem

Currently we only set the volume of the microphone track, would be nice if there was a way to do it for screen share audio too

### Describe the proposed solution

either make it configurable which sources are affected on the existing method, or add a method explicitly for screen share

### Importance

nice to have

**Comment by SimonBrandner** [comment]
I am currently working on https://github.com/vector-im/element-call/issues/1231, I have been able to make it work for user media but it would be great to be able to do it for screen-share as well

**Comment by lukasIO** [comment]
hi @SimonBrandner ,

we'll look into adding this on the participant level, too. For now you can already achieve this with this one liner
```ts
participant.getTrack(Track.Source.ScreenShareAudio).track?.setVolume(myVolume);
```

with the downside that the track has to be actually present already in order to make the adjustment. Once it's available on the participant level, it will behave the same as `participant.setVolume` does already today
