### ISSUE TITLE
could not connect PerrConnection after timeout

### ISSUE THREAD

**Issue by qljjun666** [livekit/client-sdk-js#444]
### Describe the bug

Hello, when the camera and microphone are not inserted, throw error: could not connect PeerConnection after timeout.How could I overcome this problem, thanks.

### Reproduction

const room = new Room({
    adaptiveStream: true,
    dynacast: true,
    videoCaptureDefaults: {
         resolution: VideoPresets.h720.resolution
    }
})
room.connect(...)

### Logs

```shell
Error: could not connect PeerConnection after timeout
```

### System Info

```shell
livekit-client: 1.2.9
Chrome: 96
```

### Severity

annoyance

### Additional Information

*

**Comment by lukasIO** [comment]
Hi,
you mean on a device that has no Camera or Microphone attached at all? 
Does connection work as expected if the computer in question has a microphone and or camera attached? 

Can you share the whole connection flow you're using? (also including your connect options).

**Comment by qljjun666** [comment]
[Yes.This happened without cameras and microphones.
The connection work as expected when the computer has a camera or microphone.

```
const constraints = {
      rtcConfig: { iceTransportPolicy: 'relay' },
      autoManageVideo: false,
      publishDefaults: {
        simulcast: false
      },
      audioCaptureDefaults: {
        deviceId: audioDeviceId,
        autoGainControl: false,
        echoCancellation: true,
        noiseSuppression: true
      },
      videoCaptureDefaults: {
        deviceId: videoDeviceId,
        resolution: {
          width: 1920,
          height: 1080,
          frameRate: 24
        }
      }
    }
    const room = new Room(constraints)
    try {
      room.connect(url, token)
    } catch (error) {
      console.log(error);
    }

```
](![20220923092602](https://user-images.githubusercontent.com/44661335/191877186-4a770a4d-2fef-41c1-aa41-12dd07bf4a3e.jpg))

**Comment by qljjun666** [comment]
Uncaught (in promise) Error: could not connect PeerConnection after timeout
    at eval (livekit-client.esm.mjs?23b0:21912)

**Comment by lukasIO** [comment]
Thank you for the additional details. 
The error you get is a timeout error that indicates that your livekit server didn't respond in time. The error shouldn't be tied to whether or not media devices are present on a device.
Can you replicate the error on example.livekit.io?

**Comment by qljjun666** [comment]
Press  Ctrl + Shift + N to open a new browser window.
[
![20220923163808](https://user-images.githubusercontent.com/44661335/191923060-9800c9d8-d55f-4a49-89f9-3bc834155d80.jpg)
](url)

**Comment by lukasIO** [comment]
does it work if you disable the `publish` option?

**Comment by qljjun666** [comment]
It doesn't work when  i disabled the publish option.

**Comment by lukasIO** [comment]
hm, I cannot reproduce this error. for me the connection without camera and/or microphone is working just fine:
![grafik](https://user-images.githubusercontent.com/12997837/192006593-505242d3-81da-4323-876a-e9d5aaaac7aa.png)

**Comment by qljjun666** [comment]
I'm sorry. It was my mistake.The reason is that my project runs on a LAN.I've fixed it.Thanks for your help.
