### ISSUE TITLE
Mute/Unmute events are not fired 

### ISSUE THREAD

**Issue by saintplay** [livekit/client-sdk-js#45]
Hello!

I just discovered that when a local user mutes a track: `trackPublication.mute()`.
Only `localParticipant.onTrackMuted` is fired locally. So remote peers can't be notified when this happens.

I tried to subscribe to `remoteParticipant.on(ParticipantEvent.TrackMuted)` and `room.on(RoomEvent.TrackMuted)` without luck.

Without this, there is no reactive way to update a UI when a peer user mutes/unmutes a track. (The same goes for unmute)

Additionally, version 12.0.1 of the client-sdk-js stopped emitting `localParticipant.onTrackMuted` when participant is muted by server.

Regards.

**Comment by davidzhao** [comment]
thanks for the report, we'll look into this.

**Comment by davidzhao** [comment]
Hey @saintplay, I'm not able to reproduce this. Can you try to reproduce with the sample app?

**Comment by saintplay** [comment]
Hey @davidzhao

Looking into this, the root cause of the error seems to be using `room.localParticipant.onTrackMuted` and `room.on(RoomEvent.TrackMuted, cb)` at the same time.

Removing `room.localParticipant.onTrackMuted` make this work correctly (in v 0.12.2)

Here is a [repo](https://github.com/saintplay/livekit-react/commit/7777af511f5c72c78acf453ee2e32ae0977ef83b) to reproduce that.

------

Now the problem, is using `RoomServiceClient.mutePublishedTrack(...)` in the server-sdk.
I was able to listen and react to that event using `room.localParticipant.onTrackMuted`, but now is not firing anywhere. (The last version when this was working is v0.12.0)

**Comment by davidzhao** [comment]
@saintplay yes! you should not be using `onTrackMuted` callback, that API is internal. Doing so breaks the internal event chain.

For the latter, issue, please update to the latest server build (v0.12.5 or later). It's required to support remote mute with the latest JS SDK.
