### ISSUE TITLE
LocalTrackPublication.setTrack() unmutes the local publication without an 'unmuted' event

### ISSUE THREAD

**Issue by davideberlein** [livekit/client-sdk-js#486]
#### Context
I mute and unmute the currently published audio my local  `LocalTrackPublication.unmute()/mute()`
Generally this works fine and the `muted`  and `unmuted` events are trigged as expected. However when this is combined with `LocalTrackPublication.setTrack(newTrack)` things don't seem to be consistent.

##### Steps to reproduce
mute the track using `LocalTrackPublication.mute()`
Replace the track using  `LocalTrackPublication.setTrack(newTrack)`

##### Expected behavior
*One of*
- the new track is muted and no event is emitted
- the new track is not muted and the unmuted  event is triggered
##### Actual Behavior
The track is *not muted* but *no unmuted*  event is triggered. This leaves my application in an undefined state

### Reproduction

```typescript
this.room.localParticipant.on("trackMuted" track => console.log(track.source, "muted event"));
this.room.localParticipant.on("trackUnmuted" track => console.log(track.source, "unmuted event"));

const micPublication =  await this.room.localParticipant.publishTrack(audioTrack, {
            name: "mic",
            source: Source.Microphone,
            stopMicTrackOnMute: true
        });


await micPublication.mute();
console.log("isMuted", micPublication.isMuted);
micPublication.setTrack(newTrack);
console.log("isMuted", micPublication.isMuted);
```

This is more or less what I'm doing in my application. See console output below.

### Logs

```shell
Console Output:

'microphone muted event'
'isMuted true'
'isMuted false'
```

### System Info

System: Mac OSX Version 12.5.1 (21G83)
Browser: Chrome  Version 106.0.5249.61 (Official Build) (arm64)
livekit-client: 1.4.4

### Severity

serious, but I can work around it

**Comment by lukasIO** [comment]
thanks for the report! 
One thing (that I just noticed) to keep in mind is that the `publication.setTrack` API is an internal method that is not supposed to be called by a client implementation. We mark those with an `@internal` hint. 

That said, it seems like the path of doing it via the public API with `localTrack.replaceTrack` would suffer from the same problem as you described.

**Comment by davideberlein** [comment]
> One thing (that I just noticed) to keep in mind is that the `publication.setTrack` API is an internal method that is not supposed to be called by a client implementation. We mark those with an `@internal` hint.
>

Ohh good point, I must have missed that, I'll switch to `replaceTrack` then.

**Comment by davideberlein** [comment]
@lukasIO I checked and actually `publication.setTrack` isn't set to `@internal` see: https://docs.livekit.io/client-sdk-js/classes/LocalTrackPublication.html#setTrack 
Also from an API perspective it isn't super intuitive having so many levels of management (`LocalParticipant->LocalTrackPublication->LocalTrack`) from a user perspective it's often not clear on which level you would need to do which action. I think being able to replace the Track on the `LocalTrackPublication` would be more intuitive... but it might just be me.

**Comment by lukasIO** [comment]
ah, I didn't realise it currently shows up in the API reference.
The implementation on the parent class is marked as internal (https://github.com/livekit/client-sdk-js/blob/main/src/room/track/TrackPublication.ts#L49) which also keeps it from showing up in the API reference you linked. 
The jsdocs documentation makes it sound like this hint should be inherited from the parent class, but that might also be misinterpreting things. 
> By default, if you do not add a JSDoc comment to a symbol, the symbol will inherit documentation from its parent.

My IDE still shows the inherited method as `internal` if I hover over it, but somehow this gets lost/interpreted differently when building the documentation. Might also be a bug in the `typedoc` package we are using to build that documentation.
