### ISSUE TITLE
Failed typescript compilation

### ISSUE THREAD

**Issue by nightvisi0n** [livekit/client-sdk-js#488]
### Describe the bug

Today I upgraded this library from `v1.4.1` to `v1.4.4` and since then I'm getting the following error during typescript build:  

```
node_modules/livekit-client/dist/src/index.d.ts:16:33 - error TS1005: ',' expected.

16 import RemoteVideoTrack, { type ElementInfo } from './room/track/RemoteVideoTrack';
                                   ~~~~~~~~~~~
```

I'm not sure if this is valid syntax, but I've never seen a type import together with a regular one in the same statement.

### Reproduction

```
❯ yarn tsc --version
Version 4.4.4
❯ yarn tsc
[...]
```

### System Info

```shell
System:
    OS: macOS 12.5.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 462.61 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.18.3 - ~/.nvm/versions/node/v14.18.3/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.3/bin/npm
  Browsers:
    Chrome: 106.0.5249.119
    Firefox: 105.0.3
    Safari: 15.6.1
  npmPackages:
    livekit-client: ^1.4.4 => 1.4.4 
```
```


### Severity

annoyance

### Additional Information

_No response_

**Comment by nightvisi0n** [comment]
Nevermind, upgrading `typescript` to `4.8.4` seems to fix this issue.

**Comment by davidzhao** [comment]
Thanks for raising this. @lukasIO what do you think about keeping compatibility with lower typescript versions? It seems like a hassle if we are asking users to upgrade.

**Comment by lukasIO** [comment]
Agreed. The best case scenario would be allowing this repo to use newer typescript versions but still provide compatible .d.ts files for older typescript versions. 
I found https://github.com/sandersn/downlevel-dts which seems to be the main tool to achieve this. 
I'll give it a try and open a PR if it works out.

**Comment by lukasIO** [comment]
@nightvisi0n just out of curiosity, is there a special reason why you didn't have `skipLibCheck: true` in your tsconfig?

**Comment by nightvisi0n** [comment]
I just checked the tsconfig but `skipLibCheck` is enabled in our project 🤔
