### ISSUE TITLE
How to detect if someone is speaking when muted?

### ISSUE THREAD

**Issue by MathieuLoutre** [livekit/client-sdk-js#509]
Hello! Zoom has this lovely feature that tells you if you're muted when you're speaking. Is there a way to achieve this with Livekit?

Once the local track is muted, it doesn't seem to receive any updates. Would we need to run a separate mic listener while the track is muted (and not broadcasting) or is there a way to do this with Livekit as is?

**Comment by lukasIO** [comment]
Support for this added with https://github.com/livekit/client-sdk-js/pull/515
To make sure you can still read the volume of the track even when muted, you have to pass an active track to `createAudioAnalyser` with the option `cloneTrack: true`, this will make sure that the track used for the audioAnalyser doesn't get muted when you mute the track.

**Comment by MathieuLoutre** [comment]
That's brilliant, looks nice a nice API for it too. Thank you :)
