### ISSUE TITLE
maxDecibels not respected in the new createAudioAnalyser

### ISSUE THREAD

**Issue by Uninen** [livekit/client-sdk-js#518]
### Describe the bug

I've been testing out the just merged `createAudioAnalyser` and noticed that the `maxDecibels` option is not added to the analyzer properties (near https://github.com/livekit/client-sdk-js/blob/main/src/room/utils.ts#L293)

### Reproduction

Create new `createAudioAnalyser`, see that `maxDecibels` option does not have any effect.

### System Info

```shell
N/A
```

### Severity

annoyance

### Additional Information

I'm happy to write a quick PR if it helps 👍

**Comment by lukasIO** [comment]
thanks for spotting this quickly! 
contributions are always welcome :)
