### ISSUE TITLE
Firefox fails to connect to the room

### ISSUE THREAD

**Issue by filipcro** [livekit/client-sdk-js#529]
### Describe the bug

When trying to connect to the room in Firefox, the following error is thrown, and client won't connect to the room.

```
Error: could not connect PeerConnection after timeout
```

### Reproduction

Go to some production page with the Live Kit. Bug doesn't happen on the localhost. 

Source code:
```
        const { Room, setLogLevel } = await import("livekit-client");
        setLogLevel("debug");
        room = new Room();
        await room.connect(url, token);
```

It never connects to the room. There are some rare cases when this works like it should. I also use `twilio-video` and with it everything works as expected.  

### Logs

```shell
room event connectionStateChanged 
Object { event: "connectionStateChanged", args: (1) […] }
_app-dd36f8bd8b8317f8.js:1:29678
An AudioContext was prevented from starting automatically. It must be created or resumed after a user gesture on the page. 3dbccb2b-a16b13031bf7f268.js:1:232615
connecting to wss://livekit.<domain removed>/rtc?access_token=<token removed>&auto_subscribe=1&sdk=js&version=1.5.0&protocol=8 _app-dd36f8bd8b8317f8.js:1:29678
ping config 
Object { timeout: 20, interval: 10 }
_app-dd36f8bd8b8317f8.js:1:29678
clearing ping interval _app-dd36f8bd8b8317f8.js:1:29678
start ping interval _app-dd36f8bd8b8317f8.js:1:29678
connected to Livekit Server edition: 0, version: 1.3.1, protocol: 8, region: , nodeId: ND_i6FrDJEt, debugInfo: _app-dd36f8bd8b8317f8.js:1:29678
room event signalConnected 
Object { event: "signalConnected", args: [] }
_app-dd36f8bd8b8317f8.js:1:29678
received server offer 
Object { RTCSdpType: "offer", signalingState: "stable" }
_app-dd36f8bd8b8317f8.js:1:29678
setting munged local description _app-dd36f8bd8b8317f8.js:1:29678
sending answer _app-dd36f8bd8b8317f8.js:1:29678
primary PC state changed connecting _app-dd36f8bd8b8317f8.js:1:29678
clearing ping interval _app-dd36f8bd8b8317f8.js:1:29678
room event connectionStateChanged 
Object { event: "connectionStateChanged", args: (1) […] }
_app-dd36f8bd8b8317f8.js:1:29678
room event disconnected 
Object { event: "disconnected", args: (1) […] }
_app-dd36f8bd8b8317f8.js:1:29678
Error: could not connect PeerConnection after timeout
    NextJS 45
_app-dd36f8bd8b8317f8.js:1:29678
```

### System Info

```shell
Package: `"livekit-client": "^1.5.0"`
Browser: Firefox
OS: Windows 10 and MacOS
```

### Severity

blocking all usage of LiveKit

### Additional Information

The same thing happens on the [https://livekit.io/connection-test](https://livekit.io/connection-test).

Firefox:

![image](https://user-images.githubusercontent.com/19069893/206177123-ef5c42bd-19cf-43fc-aad3-d16e1d0289c3.png)

Safari: 

![image](https://user-images.githubusercontent.com/19069893/206177214-8397cf77-12b9-44cd-94f1-c22682f3d04c.png)

I used the same URL and room token for both.

**Comment by cloudwebrtc** [comment]
@lukasIO, This may be a related issue, Firefox does not support `connectionstate` event, we may use `iceconnectionstate` to update the connection state.
https://github.com/livekit/client-sdk-flutter/issues/219#issuecomment-1340781160

**Comment by lukasIO** [comment]
thanks @cloudwebrtc, for this SDK the webrtc adapter should take care of firefox's lack of support: https://github.com/webrtc/adapter/blob/master/release/adapter.js#L1453-L1459

@filipcro I just tried the connection test from Firefox (107.0.1) and everything works as expected! 
Are you connecting to livekit-cloud or to your own instance? 
Does everything work as expected also in chrome? 
Any additional info about your setup could be helpful in figuring this out.

**Comment by filipcro** [comment]
I am connecting to my own Livekit instance that is set up on Google Cloud. The API is exposed on port 7880, I have RTC enabled on the standard ports (TCP 7881, UDP 50000-60000) and I have TURN also set up on TCP 5349 and UDP 443. The firewall is properly configured, as described in the documentation. Redis is enabled and working correctly as well. Everything works fine on the connection tester on Chrome and Safari (I get full check marks), it's only not working on Firefox. We have tested this on Widnows, Linux and MacOS, with the same results. I'm using Firefox Developer Edition 108.0b8.

**Comment by lukasIO** [comment]
thanks for the additional info, when you say
> Go to some production page with the Live Kit. Bug doesn't happen on the localhost.

are you talking about your frontend being run locally or the livekit server running locally?

**Comment by davidzhao** [comment]
@filipcro can you share the ICE candidate matrix from `about:webrtc` (see attached for example)? And in the server config, what do you set for `use_external_ip` ?
<img width="1575" alt="Screenshot 2022-12-07 at 9 56 15 AM" src="https://user-images.githubusercontent.com/320582/206259389-50ed680e-c09c-4218-81e6-4df80f3c793e.png">

**Comment by filipcro** [comment]
> are you talking about your frontend being run locally or the livekit server running locally?

Ok, that was wrong info given by me. We use different servers for development and production. The only difference between them was that development server doesn't have TURN servers enabled. We did a 

Since we found out that the problem is maybe in our deployment of the server, we did a bit of digging. We are running the server on Kubernetes with Helm, and we had an old field in the TURN server configuration that has since been removed (`loadBalancerType: gke`). I tried removing this field and also manually setting `serviceType: LoadBalancer`, and now everything seems to be working fine on all browsers.

I'm sorry for opening the issue in the wrong repo, it seamed at first that it was client related. 

@davidzhao I hope that you can use this info with another similar (or the same) issue, which you alredy saw: https://github.com/livekit/livekit/issues/1216

**Comment by lukasIO** [comment]
glad you found the root cause and got it fixed!
