### ISSUE TITLE
Participant volume change doesn't work on iOS

### ISSUE THREAD

**Issue by Uninen** [livekit/client-sdk-js#537]
### Describe the bug

iOS Safari (at least up to iOS 16.1) doesn't properly implement `HTMLMediaElement.volume` property, hence the current implementation of `participant.setVolume` doesn't work on iOS devices. The workaround is to use `AudioContext` and `gainNode`.

[RemoteAudioTrack.ts](https://github.com/livekit/client-sdk-js/blob/main/src/room/track/RemoteAudioTrack.ts) seems to have an option to attach `AudioContext` and the `setVolume` method seems to already know to use a gain node which would solve the problem. But at least in my tests, the default usage and track creation doesn't use this.

### Reproduction

Run the sample app using an iOS device or iOS Simulator; note how the volume change doesn't work. (It works fine using a desktop browser, also w/ Safari.)

### Logs

```shell
N/A
```

### System Info

```shell
System:
    OS: macOS 12.6.1
    CPU: (8) arm64 Apple M1
    Memory: 111.84 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
    Watchman: 2022.11.14.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 107.0.1
    Safari: 16.2
```

### Severity

serious, but I can work around it

### Additional Information

I haven't yet found a way to work around this but I'm assuming it can be done as we have full access to the underlying tracks and elements (this is excellent engineering! 👍)

**Comment by lukasIO** [comment]
hi @Uninen ! 
Yeah, that's a pain on iOS Safari. 
There's an experimental option `expWebAudioMix` that you can set to `true` in your `RoomOptions`. By setting this all remote audio tracks will automatically get piped through WebAudio and the `setVolume` method will take that path (via the gainNode). 
Let me know if this solves your issue!

**Comment by lukasIO** [comment]
closing as it's a browser limitation
