### ISSUE TITLE
Toggle speaker or earpiece playback in H5

### ISSUE THREAD

**Issue by Bloomingg** [livekit/client-sdk-js#574]
### Describe the bug

<img width="661" alt="image" src="https://user-images.githubusercontent.com/37789413/216943343-626cc59d-f1e3-48c3-86e1-26e49582e88a.png">
As shown in the picture, when I try to get the audio output device of the mobile terminal, I only get a default device. And the return value I obtained through the `getActiveAudioOutputDevice` method is an empty string. I tried to pass default as the device ID into `switchActiveDevice` to switch, but I failed. . .
I think maybe my operation is wrong, I want to get some guidance, thank you.

### Reproduction

const devices = await Room.getLocalDevices('audiooutput');
this.room.switchActiveDevice('audiooutput', devices[0].derviceId)

### Logs

```shell
for example in the figure above
```

### System Info

```shell
System:
    OS: macOS 12.5
    CPU: (8) arm64 Apple M1 Pro
    Memory: 316.41 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.15.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Safari: 15.6
```

### Severity

annoyance

**Comment by lukasIO** [comment]
Hi @Bloomingg,

we use this in the sample app here:
https://github.com/livekit/client-sdk-js/blob/main/example/sample.ts#L309-L322
Note that the API is only supported in Chrome right now. 
I will close this for now, feel free to open again if you hit the same problem with the example app.
