### ISSUE TITLE
Setting preferred fps doesn't work

### ISSUE THREAD

**Issue by spigelli** [livekit/client-sdk-js#576]
### What I'm expecting
Setting the preferred fps should update the fps in the example
### What I'm seeing
The preferred fps is not reflected

### Reproduction

Clone the repo and run the example.
Set add a test participant using `livekit-cli join-room --publish-demo ...`
Join the room
Set the fps to 30
Set the fps to 8
(No change)

### System Info

```shell
System:
    OS: macOS 13.0
    CPU: (10) arm64 Apple M1 Pro
    Memory: 857.33 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
  Browsers:
    Chrome: 110.0.5481.77
    Safari: 16.1
```

### Severity

blocking an upgrade

**Comment by lukasIO** [comment]
might this be an issue only when publishing from the CLI?

**Comment by davidzhao** [comment]
This is expected. It's only possible to control FPS for encodings that contain temporal layers. Currently that means AV1 and a subset of VP8 encodings. Tracks published via CLI are not encoded with temporal layers.

**Comment by spigelli** [comment]
@spiegela
