### ISSUE TITLE
enable 'selfBrowserSurface' in screen share

### ISSUE THREAD

**Issue by ShubhamJuIT** [livekit/client-sdk-js#590]
### Describe the problem

When doing Share Screen, the tab on which we are currently not visible in screen sharing options in chrome, because chrome disabled it by default. 

This issue is only happening in chrome only. Chrome disabled it bydefault to disable mirro imaging issue.

### Describe the proposed solution

Proposed solution is to pass 'selfBrowserSurface': 'include' when calling getMediaDevice()

 

### Importance

nice to have

**Comment by davidzhao** [comment]
I don't think the right solution is to override a default that Chrome decided to set. But I do agree it could make sense as an option for those that need this

**Comment by ShubhamJuIT** [comment]
@davidzhao Yes. For my requirement it is important. If you add this, it would be immensely helpful, to reduce some code duplicity and compatibility as well.

**Comment by ShubhamJuIT** [comment]
Thanks and Cheers to whole livekit team. 😄
