### ISSUE TITLE
Dependency Conflicts in Example Project

### ISSUE THREAD

**Issue by gigincg** [livekit/client-sdk-js#602]
## What I am expecting?
Successfully build the project with `npm install` command

## What is happening?
`npm install` fails due to a dependency conflict and asks to try `--force`

### Reproduction

Freshly clone the repo, cd to the `example` directory. Run `npm i`

### Logs

```shell
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: livekit-client@1.6.7
npm ERR! Found: rollup@3.18.0
npm ERR! node_modules/rollup
npm ERR!   dev rollup@"3.18.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer rollup@"^2.0.0" from rollup-plugin-terser@7.0.2
npm ERR! node_modules/rollup-plugin-terser
npm ERR!   dev rollup-plugin-terser@"7.0.2" from the root project
```
```


### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Xeon(R) E-2224G CPU @ 3.50GHz
    Memory: 28.36 GB / 31.19 GB
    Container: Yes
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
  Browsers:
    Firefox: 110.0.1
```

### Severity

annoyance

### Additional Information

I would've asked the question in slack, but I can't seem to join since it asks for a `@livekit.io` email

**Comment by lukasIO** [comment]
hi @gigincg ,
thanks for pointing this out, rollup seems to have an official terser plugin now, that doesn't have an outdated rollup peer dependency. We'll update this. 

About the slack community, which link did you use to try to sign up? It should still be possible to join without a `@livekit.io` email!

**Comment by gigincg** [comment]
@lukasIO 

The slack link in the footer in https://docs.livekit.io/ doesn't seem to be wired.

I used the link that shows up when I try to make a new Issue. It's the `livekit-users.slack.com` Workspace. Attaching a screenshot of the Slack Page:
<img width="1010" alt="image" src="https://user-images.githubusercontent.com/13028584/222979254-35036ea3-91e3-46b9-8c39-8865ee868f91.png">


Sorry for using this issue to talk about, me trying to find my way to the community

**Comment by lukasIO** [comment]
thanks raising the slack community issue, it was an outdated link that we have updated now :)
