### ISSUE TITLE
demo reports an error Room.prepareConnection

### ISSUE THREAD

**Issue by easonccc** [livekit/client-sdk-js#604]
### Describe the bug

<img width="523" alt="image" src="https://user-images.githubusercontent.com/57137923/223000245-c696b856-0d24-4de4-8958-e203f5ba95e7.png">

You can see yourself when you connect, and then you fail. And you can see yourself at first but in the Android demo you can only see the joined room, you can't see the web side of the video

### Reproduction

<img width="512" alt="image" src="https://user-images.githubusercontent.com/57137923/223001645-835232ec-5679-4e83-9cae-b8cde7091b2c.png">

I wonder why

### System Info

```shell
chrome
```

### Severity

blocking all usage of LiveKit

**Comment by lukasIO** [comment]
This looks like a misconfigured server! 
Check https://livekit.io/connection-test to make sure you've set up your server correctly.
