### ISSUE TITLE
Can't screen_share in electron

### ISSUE THREAD

**Issue by Bloomingg** [livekit/client-sdk-js#611]
### Describe the bug

When I use electron to share the screen through webrtc, I am prompted that I have no permission under windows or mac system (in fact, I have obtained the corresponding permission)

### Reproduction

localParticipant.setScreenShareEnabled(true);

### Logs

```shell
setTrackEnabled screen_share true
Room.ts:860 room event mediaDevicesError DOMException: Permission denied
```

### System Info

```shell
System:
    OS: macOS 11.3
    CPU: (8) arm64 Apple M1
    Memory: 117.47 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.16.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm
    Watchman: 2021.08.23.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 110.0.5481.177
    Safari: 14.1
  npmPackages:
    livekit-client: ^0.17.0 => 0.17.0
```

### Severity

annoyance

**Comment by lukasIO** [comment]
Hi, 
this is expected as electron doesn't support the standard `getDisplayMedia` API. 
to work around this, you can create the tracks manually yourself using the electron API https://www.electronjs.org/docs/latest/api/desktop-capturer and publish them with `localParticipant.publishTrack`

**Comment by Bloomingg** [comment]
> Hi, this is expected as electron doesn't support the standard `getDisplayMedia` API. to work around this, you can create the tracks manually yourself using the electron API https://www.electronjs.org/docs/latest/api/desktop-capturer and publish them with `localParticipant.publishTrack`

Thank you for the ideas you gave me！

**Comment by yangwooseong** [comment]
@lukasIO I'm implementing the screen share the way you suggested and it works if i do `participant.localPublish()`. But, I can't get tracks by ` useTracks([Track.Source.ScreenShare], { onlySubscribed: true})`. Do you know there can be problem when `localParticipant.publishTrack` is used directly?

**Comment by lukasIO** [comment]
I think the newer versions of electron actually implement a shim for `getDisplayMedia` so you might not need the workaround if you configure your electron app properly to support it. https://www.electronjs.org/docs/latest/api/session

When manually publishing tracks, you'll have to make sure that you assign the correct `source` yourself. 
E.g. 
```js
const localVideoTrack = new LocalVideoTrack(myAcquiredScreenShareTrack);
localVideoTrack.source = Track.Source.ScreenShare;

room.localParticipant.publishTrack(localVideoTrack)
```
