### ISSUE TITLE
Browser tab is still thinking user is using microphone but not

### ISSUE THREAD

**Issue by felixzapata** [livekit/client-sdk-js#630]
### Describe the bug

The red icon that indicates the browser is using some user device does not disappear when the user unmutes/mutes only the microphone, using `setMicrophoneEnabled`

![Captura de pantalla 2023-03-27 a las 10 17 30](https://user-images.githubusercontent.com/997038/227884714-d1ea32c3-d6b0-4600-9ada-8be1f0042598.png)

This behavior is not happening with only the video (using `setCameraEnabled`)

### Reproduction

You can use the [React live sample](https://example.livekit.io/) for this:

1. connect to a room with your camera and microphone disabled/muted.
2. unmute the microphone.
3. the user will see the icon on the browser tab.
4. mute the microphone.
5. the user still sees the icon on the browser tab.

### System Info

```shell
System:
    OS: macOS 13.1
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    Yarn: 3.5.0 - ~/.nvm/versions/node/v18.15.0/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
  Browsers:
    Chrome: 111.0.5563.110
  npmPackages:
    livekit-client: 1.7.0 => 1.7.0
```

### Severity

annoyance

**Comment by lukasIO** [comment]
Hi @felixzapata,

this behaviour is intended. It's done in order for bluetooth devices not to switch modes when muting the microphone.
You can override the behaviour by setting `stopMicTrackOnMute: true` in your room options.
