### ISSUE TITLE
Green and Purple colored video

### ISSUE THREAD

**Issue by itzloop** [livekit/client-sdk-js#684]
### Describe the bug

Hi,
With some phone using sample android client, i'm getting a green and purple video in chrome desktop. However by disabling Hardware acceleration in chrome the video is normal.
I have tested with chrome 111 and 112.
The phones i've tested were Galaxy S22 Plus and Ultra. Couldn't recreate this with other phones (i.e. s21 fe).

Both phones running Android 13
Livekit JS: livekit-client@^1.9.0
Livekit Android: 1.1.9
Livekit Server: v1.4.1

### Reproduction

Use one of S22 series phones and enable hardware acceleration in chrome. By publishing your camera feed (no difference between front and back camera modules), other peer (in chrome) will receive a green and purple image.

### System Info

```shell
our current environment

  System:
    OS: Linux 6.1 Manjaro Linux
    CPU: (16) x64 AMD Ryzen 9 6900HS with Radeon Graphics
    Memory: 5.27 GB / 14.87 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
    D. GPU: NVIDIA Geforce RTX 3070 Ti Laptop GPU
    I. GPU: AMD ATI Radeon 680M
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
```

### Severity

annoyance

### Additional Information

The picture on the right is having the bug

<a href="https://www.imgbly.com/ib/rHCEHHKlC7"><img src="https://www.imgbly.com/ib/rHCEHHKlC7.jpg" alt="rHCEHHKlC7"/></a>

**Comment by itzloop** [comment]
> to be clear, the participant who is publishing the video is using chrome on android or is using the android SDK on android?

The participant publishing the video is using the Android sdk in the sample APK, And the participant receiving the video is using chrome on desktop. There were no issues if the receiving side uses firefox (didnt check hardware acceleration tho).

**Comment by lukasIO** [comment]
cc @davidliu

**Comment by davidliu** [comment]
This sounds like this is related to https://github.com/livekit/client-sdk-android/issues/176. There's an open chromium bug to fix this issue, but until then, you'll need to use software encoding on this device to avoid this issue.

Closing this issue since it's unrelated to the JS SDK.
