### ISSUE TITLE
Local video track is not published on Chrome 74

### ISSUE THREAD

**Issue by isensen** [livekit/client-sdk-js#693]
I use livekit docker method to build my own service, and use javascript sdk to implement audio and video chatting between cell phones, most of the devices have no problem, only some of the phones have problems, the local video of these phones and the other phone video display are not a problem. But the other phone, which is communicating with him, can't receive the video screen, just like the local video screen of the phones with the problem can't be sent out, what could be the problem? What can I try?  There is no error message in the browser console, but the server found the following error message.

```
2023-05-08T02:40:38.347Z ERROR livekit supervisor/participant_supervisor.go:142 supervisor error on publication {"room": "room1683513603197 ", "roomID": "RM_CgXzUTbuajSw", "participant": "6119B8ABE206421A8DC78ECDCB40B79B", "pID": "PA_hA2bPhWGvMy8", "remote": false, "trackID": "TR _VCGULpvGnbBnGU", "error": "publish time out"}
github.com/livekit/livekit-server/pkg/rtc/supervisor.(*ParticipantSupervisor).checkPublications
        /workspace/pkg/rtc/supervisor/participant_supervisor.go:142
github.com/livekit/livekit-server/pkg/rtc/supervisor.(*ParticipantSupervisor).checkState
        /workspace/pkg/rtc/supervisor/participant_supervisor.go:131
```

Javascript SDK version : 1.7.1
Livkit Server version : 1.3.4

 Chrome version 74.0.3729.186 is causing this problem, can it be solved if I don't upgrade my browser?

**Comment by isensen** [comment]
IThank you for your reply, the browser kernel is quite old, but the current situation is due to some uncontrollable factors, I can not upgrade the browser kernel. 
I looked at it, the current code is using vp8.

**Comment by lukasIO** [comment]
does https://meet.livekit.io work from your browser?

**Comment by Drengel1990** [comment]
![image](https://github.com/livekit/client-sdk-js/assets/18291994/90d31bca-e872-49ee-bbc8-6b67c8865e68)

**Comment by Drengel1990** [comment]
Local audio track issue

**Comment by isensen** [comment]
@lukasIO  @davidzhao 
Thank you for your reply, If I use [https://meet.livekit.io](https://meet.livekit.io) to test, it will report an error: 
`react-dom.production.min.js:189 TypeError: Failed to construct 'IntersectionObserver': member root is not of type Element.`

In fact, I also encountered this problem in my code, the error is caused by inconsistent implementation of IntersectionObserver in different versions of chrome, which I replaced using polyfill. (I'm not sure if this is causing the problem)
[Feature: IntersectionObserver Document Root](https://chromestatus.com/feature/5714474851893248)
[polyfill ](https://github.com/GoogleChromeLabs/intersection-observer/blob/main/intersection-observer.js): Remove lines 19 to 34
 
You can try to download a corresponding version of chome to test the problem. (Use a high version of chrome and a low version of chrome for the meeting.)
[Chromium History Versions Download](https://vikyd.github.io/download-chromium-history-version/#/)

**Comment by isensen** [comment]
Thank you for your reply.
My English is not very good, so I may not have described it clearly,  chrome74 could see the local and remote video, but the newer versions of chrome can't see the remote video(published from chrome74).

 I've tried setting adaptiveStream to false, but the problem still persists.

**Comment by lukasIO** [comment]
thanks! 
I understood your description just fine, only wanted to make sure that I am looking at the right thing :) 
I confirmed what you described on chrome v74 and also confirmed that #703 fixes the issue. Once the next livekit-client version gets released, the fix will be part of it.

**Comment by isensen** [comment]
Thanks !  I'm looking forward to the next version. :)
