### ISSUE TITLE
 How to mute other users?

### ISSUE THREAD

**Issue by Drengel1990** [livekit/client-sdk-js#704]
### Describe the problem

Hello. How to mute other users. For example, there are me and two more users in the room. And I want to have the ability to mute them. So they can talk to each other but I can't hear them!

### Describe the proposed solution

I suggest adding a method that will mute and unmute other users.

### Importance

nice to have

**Comment by lukasIO** [comment]
Hi, 
there's two ways to effectively mute a Track/Participant locally:
```
remoteParticipant.setVolume(0);
// or
remoteParticipant.getTrack(Track.Source.Microphone).setEnabled(false);
```
