### ISSUE TITLE
device. label appears empty

### ISSUE THREAD

**Issue by xubaobao19940428** [livekit/client-sdk-js#737]
### Describe the problem

Hello, in browsers with other kernels, device. label appears empty because

If the label in the device list obtained by enumerateDevices() is empty without obtaining media permissions first, then the device name cannot be recognized?

### Describe the proposed solution

Open case projects in browsers of other kernels

### Importance

nice to have

### Additional Information

Hello, in browsers with other kernels, I would like to recognize the device name

**Comment by xubaobao19940428** [comment]
感谢您的回复，是我用了这个 Room.getLocalDevices api,会自动请求权限，底下是代码的片段，您们的事例项目livekit-react可以在安卓设备的浏览器中也是无法显示的
`function createMediaDeviceObserver(kind?: MediaDeviceKind, requestPermissions = true) {
  const onDeviceChange = async () => {
    const newDevices = await Room.getLocalDevices(kind, requestPermissions);
    deviceSubject.next(newDevices);
  };
  const deviceSubject = new Subject<MediaDeviceInfo[]>();

  const observable = deviceSubject.pipe(
    finalize(() => {
      navigator?.mediaDevices?.removeEventListener('devicechange', onDeviceChange);
    }),
  );

  if (typeof window !== 'undefined') {
    if (!window.isSecureContext) {
      throw new Error(
        `Accessing media devices is available only in secure contexts (HTTPS and localhost), in some or all supporting browsers. See: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/mediaDevices`,
      );
    }
    navigator?.mediaDevices?.addEventListener('devicechange', onDeviceChange);
    // because we rely on an async function, trigger the first update instead of using startWith
    onDeviceChange();
  }
  return observable;
}`
`/** @public */
export function useMediaDevices({ kind }: { kind: MediaDeviceKind }) {
  const deviceObserver = React.useMemo(() => createMediaDeviceObserver(kind), [kind]);
  const devices = useObservableState(deviceObserver, []);
  return devices;
}

/** @public */
export interface UseMediaDeviceSelectProps {
  kind: MediaDeviceKind;
  room?: Room;
}

/** @public */
export function useMediaDeviceSelect({ kind, room }: UseMediaDeviceSelectProps) {
  const roomContext = useMaybeRoomContext();
  // List of all devices.
  const deviceObserver = React.useMemo(() => createMediaDeviceObserver(kind), [kind]);
  const devices = useObservableState(deviceObserver, []);
  // Active device management.
  const [currentDeviceId, setCurrentDeviceId] = React.useState<string>('');
  const { className, activeDeviceObservable, setActiveMediaDevice } = React.useMemo(
    () => setupDeviceSelector(kind, room ?? roomContext),
    [kind, room, roomContext],
  );
`

**Comment by xubaobao19940428** [comment]
Thank you for your reply. I used this Room.getLocalDevices api, which will automatically request permission. Below is a code snippet. Your example project livekit-react can’t be displayed in the browser of an Android device.



`function createMediaDeviceObserver(kind?: MediaDeviceKind, requestPermissions = true) {
  const onDeviceChange = async () => {
    const newDevices = await Room.getLocalDevices(kind, requestPermissions);
    deviceSubject.next(newDevices);
  };
  const deviceSubject = new Subject<MediaDeviceInfo[]>();

  const observable = deviceSubject.pipe(
    finalize(() => {
      navigator?.mediaDevices?.removeEventListener('devicechange', onDeviceChange);
    }),
  );

  if (typeof window !== 'undefined') {
    if (!window.isSecureContext) {
      throw new Error(
        `Accessing media devices is available only in secure contexts (HTTPS and localhost), in some or all supporting browsers. See: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/mediaDevices`,
      );
    }
    navigator?.mediaDevices?.addEventListener('devicechange', onDeviceChange);
    // because we rely on an async function, trigger the first update instead of using startWith
    onDeviceChange();
  }
  return observable;
}`

**Comment by lukasIO** [comment]
this sounds like a different issue regarding `components-js`? If so, feel free to open an issue on that repo and fill out the bug report form!
