### ISSUE TITLE
Calling RemoteVideoTrack.attach always results in a warning

### ISSUE THREAD

**Issue by HermanBilous** [livekit/client-sdk-js#744]
### Describe the bug

When I call RemoteVideoTrack.attach no warnings are produced.

Instead a warning "RemoteVideoTrack.ts:44 When using adaptiveStream, you need to use remoteVideoTrack.attach() to add the track to a HTMLVideoElement, otherwise your video tracks might never start" is logged.

The issue comes from calling
```
    attachToElement(this.mediaStreamTrack, element);
```
in Track.ts

### Reproduction

run `yarn sample`, connect with 2 participants

### System Info

```shell
not relevant
```

### Severity

annoyance

**Comment by lukasIO** [comment]
sorry about that, will be fixed by https://github.com/livekit/client-sdk-js/pull/742
