### ISSUE TITLE
Discrepancy in property `attachedElements` of `Track` object of `RoomEvent` `TrackSubscribed` and `TrackUnsubscribed`

### ISSUE THREAD

**Issue by pabloFuente** [livekit/client-sdk-js#749]
### Describe the bug

This might be a conscious design decission (not storing any kind of state locally). But just in case I'm going to expose what I expected to find and what I found when setting the handlers for the TrackSubscribed and TrackUnsubscribed Room events.

### What I'm expecting

I hoped that after calling `Track.attach` inside the `TrackSubscribed` handler, the Track object would store the information about the attached HTML elements not only in that specific variable, but also across events.

### What happens instead

When handling event `TrackUnsubscribed` for the same `Track`entity, the object passed to the event's handler has its `attachedElements` array empty.

> As I said, this could be a simple decission not to store any state locally and leave full responsibility for state management to the application. But if livekit-client handled it internally, in many cases the code could be greatly simplified.

### Reproduction

Join two different participants to the same room with this code:

```js
var room = new LivekitClient.Room();

room.on(LivekitClient.RoomEvent.TrackSubscribed, (track) => {
	track.attach();
	console.log(`TrackSubscribed: showing attached elements of track ${track.sid} (${track.attachedElements})`);
});

room.on(LivekitClient.RoomEvent.TrackUnsubscribed, (track) => {
	console.log(`TrackUnsubscribed: showing attached elements of track ${track.sid} (${track.attachedElements})`);
});

await room.connect(livekitUrl, accessToken);
room.localParticipant.setMicrophoneEnabled(true);
room.localParticipant.setCameraEnabled(true)
```

This will log the following on the browser's console:

![image](https://github.com/livekit/client-sdk-js/assets/15049534/b17833e2-330e-44d5-acb2-339eb825d65f)

### System Info

```shell
- livekit-client package (1.10.0) being used in a plain JS application
- Google Chrome Version 114.0.5735.133 (Official Build) (64-bit)
```

### Severity

annoyance

**Comment by davidzhao** [comment]
It does retain `attachedElements` across events. However, what you are seeing here is the SDK automatically detaching from all attached elements upon unsubscribe.

When the track is unsubscribed, the attachment is removed automatically.
