### ISSUE TITLE
Issue connecting to room using node js

### ISSUE THREAD

**Issue by qiblatainf** [livekit/client-sdk-js#763]
### Describe the bug

.connect() method is not a constructor, but a string. Therefore, if I pass the URL and Token in it, it does not connect to the room. 

### Reproduction

const { Room } = require('livekit-client');
const URL = ' '
const TOKEN = ' '
async function roomConnect(){
    const room = new Room();
    await room.connect(URL, TOKEN);
    
    console.log('connected to room', room.name);
}

roomConnect();

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
    Memory: 10.16 GB / 19.92 GB
  Binaries:
    Node: 18.14.2 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (114.0.1823.67)
    Internet Explorer: 11.0.19041.1566
```

### Severity

blocking all usage of LiveKit

**Comment by lukasIO** [comment]
Hi, 

nodejs is currently not supported with the client-sdk-js.
There might be efforts to enable this in the future, but nothing on an immediate roadmap, sorry.
