### ISSUE TITLE
[1.11.0+] createLocalScreenTracks returns `ended` tracks

### ISSUE THREAD

**Issue by burzomir** [livekit/client-sdk-js#770]
### Describe the bug

I first discovered this while working with createLocalScreenTracks.  LocalTrack calls super(), which leads to setting this_mediaStreamTrack. Then it calls setMediaStreamTrack, which stops this._mediaStreamTrack if it is set.

```
1. LocalTrack.constructor(mediaStreamTrack) -> 
Track.constructor(mediaStreamTrack) -> 
this._mediaStreamTrack = mediaStreamTrack

2. LocalTrack.constructor(mediaStreamTrack) -> 
LocalTrack.setMediaStreamTrack(mediaStreamTrack) -> 
if (this._mediaStreamTrack) { this._mediaStreamTrack.stop() }
```

### Reproduction

Use createLocalScreenTracks. Returned track `readyState` is already `ended.`

### System Info

```shell
Any os, any browser.
```

### Severity

blocking all usage of LiveKit

**Comment by lukasIO** [comment]
thanks for the report, fixed with https://github.com/livekit/client-sdk-js/pull/769
