### ISSUE TITLE
Laggy screen share

### ISSUE THREAD

**Issue by Vaib215** [livekit/client-sdk-js#777]
### Describe the bug

In focus layout, the video streams of all the participants are visible at same time. I want that when the screen is shared, only the visible streams should get loaded and rest others should not get loaded. Currently, there're are 200 people with video on, each subscriber is getting all the 200 video streams at once. How to load only the visible streams? Please help

### Reproduction

When 200 participants join and share video then on screen share, it is laggy and low resolution.

### System Info

```shell
Smartphone (iOS & Android)
Windows
macOS
```

### Severity

blocking all usage of LiveKit

### Additional Information

Need urgent help

**Comment by davidzhao** [comment]
you'd need to use selective subscriptions to ensure you are paging correctly. the same question had been responded to in Slack, leaving the answer here as well in case it helps others.
