### ISSUE TITLE
Uncaught (in promise) DOMException: Requested device not found

### ISSUE THREAD

**Issue by MMR-learning** [livekit/client-sdk-js#784]
### Describe the bug

sample.ts:202 Uncaught (in promise) DOMException: Requested device not found

### Reproduction

sample.ts:202 Uncaught (in promise) DOMException: Requested device not found

### Logs

```shell
sample.ts:202 Uncaught (in promise) DOMException: Requested device not found
```

### System Info

```shell
sample.ts:202 Uncaught (in promise) DOMException: Requested device not found
```

### Severity

annoyance

### Additional Information

sample.ts:202 Uncaught (in promise) DOMException: Requested device not found

**Comment by lukasIO** [comment]
this needs more info with steps to reproduce.

**Comment by MMR-learning** [comment]
Does the https protocol have to be required? I have a problem with the local Intranet deployment.

**Comment by lukasIO** [comment]
yeah, accessing a local deployment outside of the host itself requires https! 

for your problem, it's either the missing https or the fact that the sample calls `enableCameraAndMicrophone` and your device does not have one of these.
