### ISSUE TITLE
createLocalAudioTrack method does not work for more than 16 tabs

### ISSUE THREAD

**Issue by Drengel1990** [livekit/client-sdk-js#795]
### Describe the bug

createLocalAudioTrack method does not work for more than 16 tabs
That is, suppose I open one room in 16 tabs and everything is fine. More than 16 does not trigger createLocalAudioTrack and gives the error could not start audio source

### Reproduction

That is, suppose I open one room in 16 tabs and everything is fine. More than 16 does not trigger createLocalAudioTrack and gives the error could not start audio source

### Logs

```shell
Uncaught (in promise) DOMException: Could not start audio source
```

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 AMD Ryzen 5 5600H with Radeon Graphics
    Memory: 8.56 GB / 27.86 GB
  Binaries:
    Node: 14.21.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.18 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1992.0), Chromium (114.0.1823.82)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    livekit-client: ^1.12.1 => 1.12.1
```

### Severity

serious, but I can work around it

### Additional Information

Uncaught (in promise) DOMException: Could not start audio source

**Comment by davidzhao** [comment]
this is likely a limitation with Chrome, where it's unable to acquire the same audio source more than N times.

since this is an atypical use case for end users, and the fact that we do not have controls over browser limits, I'm closing the issue as `wontfix`
