### ISSUE TITLE
LocalParticipant.setCameraEnabled() leaks stream if publish fails

### ISSUE THREAD

**Issue by dbkr** [livekit/client-sdk-js#797]
### Describe the bug

When calling LocalParticipant.setCameraEnabled(), the stream is leaked (ie. the webcam light remains on) if the setTrackEnabled() method re-enables the track but the publishing fails.

In this case, this was because LiveKit disconnected the call after it timing out from having no Internet. The camera track was automatically disabled when it disconnected, but if we try to re-enable the camera, the webcam light stays on until the tab is refreshed. In this case it was obviously a bug that we were calling that method with the call disconnected, but I would still expect the stream to not leak.

I suspect setTrackEnabled should just catch errors from failing to publish the stream and close the track again if it re-opened it?

### Reproduction

Call `LocalParticipant.setCameraEnabled()` with the livekit call in a disconnected state (hopefully this is enough given the detail above?)

### System Info

```shell
Livekit client JS 1.12.0, Google Chrome 114.0.5735.198
```

### Severity

annoyance

**Comment by lukasIO** [comment]
thanks @dbkr for the report! 
Opened a PR to address this
