### ISSUE TITLE
ShareScreen on Electron Returns  DOMException: Not supported

### ISSUE THREAD

**Issue by YoussefLaunchUp** [livekit/client-sdk-js#823]
**Describe the bug**
ShareScreen on Electron Returns  DOMException: Not supported and does not share screen.

**Server**
Using cloud livekit

**Client**
- React, electron
- "@livekit/components-react": "^1.0.5"
- "livekit-client": "^1.10.0"

**To Reproduce**
1. Client joins with screen set to true. DOMException: Not supported logged and to screen shared

**Expected behavior**
Screen to be shared

**Screenshots**
Relevant code
``` 
<LiveKitRoom
          room={room}
          token={token}
          serverUrl={wsURL}
          connect={connect}
          onConnected={() => setIsConnected(true)}
          onDisconnected={handleDisconnect}
          audio={true}
          video={{
            resolution: {
              width: 192,
              height: 144
            },
            facingMode: 'user'
          }}
          screen={true}
        >
```

**Additional context**
Might have to do with Screen Capture api working differently on electron. Would appreciate any possible workaround to get screen sharing to work on electron.

**Comment by lukasIO** [comment]
electron now supports `getDisplayMedia`, you'll need to work with `desktopCapturer` to make that work.
Here are the docs: https://www.electronjs.org/docs/latest/api/session#sessetdisplaymediarequesthandlerhandler. 

Let me know if that approach still fails for you, then I'll reopen the issue.

**Comment by YoussefLaunchUp** [comment]
@lukasIO Thanks for the reference. I was aware that I need to use electron's `desktopCapturer` but I am unsure how to incorporate it with livekit. Is there a way to have livekit use desktopCapturer instead of `navigator.MediaDevices.GetDisplayMedia` API?
