### ISSUE TITLE
Track is paused even without using adaptiveStream

### ISSUE THREAD

**Issue by sebsken** [livekit/client-sdk-js#831]
### Describe the bug

First off, I am not sure if this is a bug or by design but for me this is unexpected behavior as adaptiveStream actually has a feature to pause a track if it is hidden. See here https://docs.livekit.io/client/receive/#adaptive-stream and here https://github.com/livekit/client-sdk-js/blob/f7c4c96027d104e0cad46c5e47d7ca3919f4afc5/src/room/track/types.ts#L24

So I would expect that if adaptiveStream is disabled we do not have this behavior.

### Setup
Use the sample app to connect two people without using adaptiveStream and have a canvas duplicate the content of the remote video stream. For instance, this enables doing some real time video processing on the client side.

### Expectation
I can hide the video element to which the remote track is attached and the canvas content will still be updated/the track will not be paused.
OR I can scroll down to only see the canvas and it keeps being updated

### Actual result
The remote track is paused and thus the canvas is not updated anymore.

### Reproduction

See description section and the sample app in this repo https://github.com/sebsken/client-sdk-js

### Logs
There are no particular logs for this.

### System Info
OS: Windows
Browser: edge version 115.0.1901.188, same bug on chrome 115.0.5790.171

On Android the bug also happens but only when the canvas is put to full screen (tested on both edge and chrome).

### Severity

blocking all usage of LiveKit

### Additional Information

We could fix this bug around this line of code
https://github.com/livekit/client-sdk-js/blob/f7c4c96027d104e0cad46c5e47d7ca3919f4afc5/src/room/track/Track.ts#L94C5-L95C39

I am not sure if we can check the property of the adaptiveStreamSetting pauseVideoInBackground but the least we could do is provide a parameter in the function signature:
```js
attach(element?: HTMLMediaElement, ignoreVisibility = false): HTMLMediaElement {
...

if (this.attachedElements.length === 0 && Track.Kind.Video && !ignoreVisibility ) {
      this.addAppVisibilityListener();
    }
```

The only workaround I have found is to have a separate copy of livekit sdk with the fix mentioned here. Or plainly not add the listener.
I tried to find the exact event that triggers the track to be stopped/muted but I could not.

As an extra note, while investigating this bug, I think I found another one here: https://github.com/livekit/client-sdk-js/blob/f7c4c96027d104e0cad46c5e47d7ca3919f4afc5/src/room/track/RemoteVideoTrack.ts#L225

When `this.adaptiveStreamSettings?.pauseVideoInBackground` is false, then we should never pause the video so this
`(this.elementInfos.some((info) => info.visible) && !backgroundPause)`
should instead be
`(this.elementInfos.some((info) => info.visible) || !backgroundPause)`

**Comment by lukasIO** [comment]
Thanks for the detailed report. 

I was trying to reproduce the behaviour you describe, but failed to do so. 
I cloned the reproduction repository and connected two clients. For both clients I made sure that `adaptiveStream` is `false` and then scrolled down to only see the two canvas objects. The canvases keep updating for me. 
Did I miss anything? 

WRT to 
> As an extra note, while investigating this bug, I think I found another one here:

This code path only gets triggered if `adaptiveStream` is enabled in the first place, `updateVisibility` should not be called otherwise.

**Comment by sebsken** [comment]
Thank you for looking into this @lukasIO .

Actually, when you scroll down, you do not see two canvas objects. The upper video is an html video element to which the remote track is attached. `<video id="video-test"></video>`
The lower "video" is the actual canvas `<canvas id="canvas-test" width="1920px" height="1080px"></canvas>`.

And if your screen resolution is not bigger than full HD (1080px vertically) you should be able to scroll down enough and have **only** the canvas visible. The video element is not visible at all. Then the video stops.

To make it easier, I updated the example repo with a spacer html element so that you can scroll down and have only the canvas element visible.

About the code path which is only triggered when `adaptiveStream` is enabled, I know this. I tried to use it as a workaround but it did not work because of the bug I mentioned. When you reproduce the issue with `adaptiveStream` disabled, you can try to enable `adaptiveStream` with `pauseVideoInBackground ` set to `false` and it also produces the issue that the track is paused.

**Comment by lukasIO** [comment]
hm, that didn't help. Made sure that only the canvas is in view, but it just kept playing. 


> When this.adaptiveStreamSettings?.pauseVideoInBackground is false, then we should never pause the video so this

maybe that's a misunderstanding then, `pauseVideoInBackground` means pause it _also_ when the tab is in the background, not only if it's offscreen. So adaptive stream will still work as normal with `pauseVideoInBackground: false` it just won't pause if the elements are _only_ in background but would be visible on the page.

**Comment by sebsken** [comment]
Ok, I thought it would be easier to reproduce :-)
I realize that I serve the sample app with an https server and with a private livekit server (don't remember the version but it is from June I think).
So I will test it with a livekit cloud server and running the website locally with yarn vite sample to see if there is any difference.
Then if I can't find a configuration where the problem goes away, I will make a screen recording and share it here so you can hopefully reproduce it on your end. If not... we shall see :-)
That will take me a while (I don't have a ton of time available to work on this) but it should be done by my Sunday night at the latest.

**Comment by lukasIO** [comment]
thanks for the additional repro steps. I'm still not able to reproduce.
What I don't see in the video is you actually connecting. So I'm wondering if you disable `adaptiveStream` _prior_ to connecting or only _after_? 
`adaptiveStream` is a one-off connection time setting, so changing the value will only have an effect _before_ pressing `connect`. 

in case this doesn't help, do you want to join the [community chat ](https://join.slack.com/t/livekit-users/shared_invite/zt-rrdy5abr-5pZ1wW8pXEkiQxBzFiXPUg) to discuss this further? Happy to send you a video of my attempt to reproduce it there. I'm `@lukasIO` on there as well.

**Comment by sebsken** [comment]
Hello,
Good point and yes, I did disable it before connecting. On both ends of the connection. I actually restarted the test once because I had forgotten this.

I can also confirm that on android I have the same issue when put in fullscreen and I tested on windows 11 with a 2k screen resolution and it also happens.

Happy to join the community chat to review this further, yes. I don't have an appropriate email address to join it. Can you invite me?

I have some extra ideas that I will try today and see how it goes.
Namely, I am wondering if the html video element does not get paused and edge has a feature to take a screenshot of an entire webpage including the hidden part of it. So I wonder what this will look like. I'll let you know how this goes.

**Comment by sebsken** [comment]
Ok, I was annoyed because in webrtc-internals it would still use enough bandwidth to show that the video track was not paused.
It turns out that the *html video element* gets paused when it is hidden. That should narrow down the search scope.
Simply calling `document.getElementById('video-test').play()` anytime the pause event is fired on the element is a good workaround but it would be nice to figure out why the video is paused in the first place.

**Comment by sebsken** [comment]
It worked! Thanks.

**Comment by lukasIO** [comment]
dicussed this further with @sebsken on slack and we agreed that we're not going to fix the issue within the SDK. 

For future reference, @sebsken tracked the issue down to be related to the `autoplay` property present on the video element. SDK wise we're weary that removing it would cause other intended side effects on some browsers.
