### ISSUE TITLE
Support relative URLs

### ISSUE THREAD

**Issue by Montellese** [livekit/client-sdk-js#853]
### Describe the problem

First off, let me thank you for this great piece of open source software!

Right now when calling `Room.prepareConnection()` or `Room.connect()` with a relative URL like `/` or `/video` an exception is thrown at https://github.com/livekit/client-sdk-js/blob/ab1e1d696ba3b76417734adc711be4af54fac85b/src/room/Room.ts#L365 / https://github.com/livekit/client-sdk-js/blob/ab1e1d696ba3b76417734adc711be4af54fac85b/src/room/Room.ts#L404 because the `URL` constructor cannot handle relative paths. This is the console output:

```
could not prepare connection
TypeError: Failed to construct 'URL': Invalid URL
```

In my case, the whole `isCloud()` code path is irrelevant since I'm running the LiveKit server on premise. From a quick glance, the rest of the code should be fine since it's not using `URL` but there could be other code parts which expect a full URL.``

### Describe the proposed solution

Support relative URLs `/` or `/video` to be able to provide the LiveKit endpoint on the same web server or reverse proxy as the web UI.

### Importance

would make my life easier

**Comment by lukasIO** [comment]
hi! 
is there anything keeping you from just constructing the full URL before passing it with something like `window.location` ?

**Comment by Montellese** [comment]
That's what I'm doing right now as a workaround. But in general I try to avoid absolute URLs if it's not absolutely necessary, especially if the endpoints are hosted by the same webserver.

**Comment by lukasIO** [comment]
one problem with that would be that the livekit client sdk wouldn't know which protocol you'd want to use (`ws` vs `wss`) in relative URLs. 
In the end we would only shift constructing the absolute URLs into the SDK, I don't think that's preferable. 
Will close this as not planned.
