### ISSUE TITLE
Setting custom adaptiveStream pixelDensity leads to type error

### ISSUE THREAD

**Issue by davideberlein** [livekit/client-sdk-js#865]
### Describe the bug

As discussed with @lukasIO a while ago on [Slack](https://livekit-users.slack.com/archives/C01KVTJH6BX/p1687160935915069) LiveKit automatically falls back to a pixel density of `1` if the screen has a pixel density of up to `2`. As this leads to a bad UX on e.g. MacBook pros I have implemented my own detection which returns the following:
`screen < 1.5 -> 1` 
`screen <= 2 -> 1.5`
`screen < 2 -> 2`

In general this works fine, however it seems like the adaptive screen video dimension calculation doesn't do any rounding of the detected playback size and then ends up with a type error because it expects a `uint` but receives a floating value. See the attached screenshot

<img width="909" alt="image" src="https://github.com/livekit/client-sdk-js/assets/3438183/f4e08c15-5ee6-4343-90c8-f8995a82d7dc">

### Reproduction

set the RoomOptions `adaptiveStream.pixelDensity` to `1.5` and change the size of the played back video until it hits an uneven pixel size.

### Logs

```shell
RemoteTrackPublication.ts:285 adaptivestream video dimensions 540x304.5 {trackSid: 'TR_VCCPgzitFZfM6F'}
SignalClient.ts:547 error sending signal message {error: Error: invalid uint 32: 304.5}
```

### System Info

```shell
M1 MacBook Pro (2021)
Chrome 116
```

### Severity

serious, but I can work around it

**Comment by lukasIO** [comment]
discussed on slack, this got fixed in https://github.com/livekit/client-sdk-js/pull/846
