### ISSUE TITLE
The requested module 'livekit-client' does not provide an export named 'Room'

### ISSUE THREAD

**Issue by Nodalailama** [livekit/client-sdk-js#880]
### Describe the bug

When I am using the latest version, the 'livekit-client' module does not provide an export named 'Room'

### Reproduction

Use the latest version and you should see the problem.

### Logs

```shell
SyntaxError: The requested module 'livekit-client' does not provide an export named 'Room'
or
 SyntaxError: The requested module 'livekit-client' does not provide an export named 'ConnectionQuality'
```

### System Info

```shell
macos, brave using 
"https://cdn.jsdelivr.net/npm/livekit-client/dist/livekit-client.umd.min.js"
or
"https://ga.jspm.io/npm:livekit-client@1.13.3/dist/livekit-client.esm.mjs"
```

### Severity

blocking all usage of LiveKit

**Comment by davidzhao** [comment]
Please follow instructions in the [README](https://github.com/livekit/client-sdk-js#minified-js). You need to prefix references with `LivekitClient` like `LivekitClient.Room`

**Comment by Nodalailama** [comment]
Ok.
