### ISSUE TITLE
Metadata update event doesn’t fire when metadata first set 

### ISSUE THREAD

**Issue by gabrieljbaker** [livekit/client-sdk-js#887]
### Describe the bug

I am listening for participant metadata updates but I see that these update events don’t fire when a participant first sets their metadata, it only seems to fire once the metadata has been changed from that point onwards. 

Is that expected behavior? To me, a change from empty to something in the metadata would certainly be considered a change that should fire the metadata update listener. 

Relatively new to the API, so if in misunderstanding something I’ll be happy to be called out! :)

### Reproduction

Go into a room with two participants with participant metadata update listeners, and notice that initially setting the metadata for one of them won’t fire the listener for the other - only after initially setting it and then changing it will the update listener fire for the other participant. 

### System Info

```shell
Mac OSX, Chrome
```

### Severity

serious, but I can work around it

**Comment by lukasIO** [comment]
hi @gabrieljbaker , 
Could you provide a minimal example repo for this issue? thanks!

**Comment by PrasanthGondi** [comment]
@gabrieljbaker Did you find any way to fix this?
