### ISSUE TITLE
MacOS 14 Safari screen sharing low quality 

### ISSUE THREAD

**Issue by bell-101** [livekit/client-sdk-js#890]
### Describe the bug

Hey all! After upgrading MacOS to version 14 [Sonoma], Safari always has poor screen sharing quality. Is there any ways to fix it?

### Reproduction

- Upgrade your MacOS to 14
- Open Safari
- Go to the https://meet.livekit.io
- Select Demo
- Click Start meeting
- Share screen

### System Info

```shell
MacOS 14, Safari
```

### Severity

annoyance

**Comment by davidzhao** [comment]
Fixed in https://github.com/livekit/client-sdk-js/releases/tag/v1.14.0

**Comment by davidzhao** [comment]
This is a bug introduced in Safari 17: https://bugs.webkit.org/show_bug.cgi?id=263015
