### ISSUE TITLE
Cannot find name 'RTCEncodedVideoFrame'

### ISSUE THREAD

**Issue by pemartini94** [livekit/client-sdk-js#925]
### What is happening: 
After npm install and ng serve, this is the error I got (tested multiple apps):

`Error: node_modules/livekit-client/dist/src/e2ee/utils.d.ts:4:100 - error TS2304: Cannot find name 'RTCEncodedVideoFrame'.

4 export declare function isVideoFrame(frame: RTCEncodedAudioFrame | RTCEncodedVideoFrame): frame is RTCEncodedVideoFrame;
`

### Reproduction

npm install livekit-client

ng serve

### System Info

```shell
livekit.client@1.14.4
@types/webrtc@0.0.39
```

### Severity

blocking all usage of LiveKit

### Additional Information

Testing with the sample seems to work, but the package is broken.

**Comment by pemartini94** [comment]
+Adding the flag allows the lib to work properly:

`"skipLibCheck": true`

**Comment by lukasIO** [comment]
Which typescript version are you using in your project?

**Comment by pemartini94** [comment]
Hi @lukasIO, currently using typescript@4.6.2

**Comment by lukasIO** [comment]
this type seems to have only landed in the TS DOM lib in 4.7 (see https://github.com/microsoft/TypeScript/blame/main/src/lib/webworker.generated.d.ts)

Is it possible for you to upgrade to 4.7?

**Comment by lukasIO** [comment]
closing due to missing feedback
