### ISSUE TITLE
communication  between client-sdk-js --- client-sdk-flutter

### ISSUE THREAD

**Issue by no-1ne** [livekit/client-sdk-js#937]
### Describe the problem

looking to send webrtc stream from flutter to a webview within flutter app, is it possible to do it without much effort..

### Describe the proposed solution

currently its designed to talk to server side looking to use it as a p2p thing 

### Importance

would make my life easier

**Comment by lukasIO** [comment]
Hi, 
communication between the client-sdk-flutter and client-sdk-js works out of the box. 
WebView support is always tricky though. We don't have any official guidelines on how to make that work.

Feel free to ask general questions in the [community chat on slack 
](https://livekit.io/join-slack)
