### ISSUE TITLE
Attempted import error: 'LocalParticipant' is not exported from 'livekit-client'

### ISSUE THREAD

**Issue by jornatf** [livekit/client-sdk-js#938]
### Describe the bug

When I copy/paste **Quickstart code for Nextjs** ([link here](https://docs.livekit.io/realtime/quickstarts/nextjs-13/)) and I follow this example, I have this error:

![image](https://github.com/livekit/client-sdk-js/assets/92311176/a200a45c-0eb1-46f8-8d4e-8d2751451bd0)

### Reproduction

Follow instructions here: [https://docs.livekit.io/realtime/quickstarts/nextjs-13/](https://docs.livekit.io/realtime/quickstarts/nextjs-13/)

### System Info

```shell
System:
- OS: Windows 10 10.0.19044
- CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
- Memory: 5.46 GB / 15.69 GB

Binaries:
- Node: 19.2.0 - C:\Program Files\nodejs\node.EXE
- npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD

Browsers:
- Chrome: 119.0.6045.125
- Edge: Spartan (44.19041.1266.0), Chromium (119.0.2151.58)
- Internet Explorer: 11.0.19041.1566

npmPackages:
-livekit-client: ^1.15.0 => 1.15.0
```

### Severity

blocking all usage of LiveKit

**Comment by Ocupe** [comment]
Thank you for your report! Can you tell us which version of Next.js you are using?
Did you add the 'use client' to the component?
<img width="801" alt="image" src="https://github.com/livekit/client-sdk-js/assets/11357413/8450e891-f6aa-4d7e-a8f0-af47df3d0e95">

**Comment by jornatf** [comment]
Yes I did.

Dependencies version:

```
...
"dependencies": {
    "@livekit/components-react": "^1.4.0",
    "@livekit/components-styles": "^1.0.7",
    "livekit-client": "^1.15.0",
    "livekit-server-sdk": "^1.2.7",
    "next": "14.0.2",
    "react": "^18",
    "react-dom": "^18"
  },
  "devDependencies": {
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "autoprefixer": "^10.0.1",
    "eslint": "^8",
    "eslint-config-next": "14.0.2",
    "postcss": "^8",
    "tailwindcss": "^3.3.0",
    "typescript": "^5"
  }
...
```

**Comment by lukasIO** [comment]
For some reason nextjs (or rather webpack) seems to choke on the `.mjs` extension of `livekit-client`'s dist package. 
some issues for reference:
https://github.com/ReactTooltip/react-tooltip/issues/1122
https://github.com/vercel/next.js/issues/39375

One workaround, that works for me is to add this nextjs config: 
```js
/** @type {import('next').NextConfig} */

const nextConfig = {
  webpack: (
    config,
    { buildId, dev, isServer, defaultLoaders, nextRuntime, webpack }
  ) => {
    config.module.rules.push({
      test: /\.mjs$/,
      include: /node_modules/,
      type: "javascript/auto",
    });
    return config;
  },
};

module.exports = nextConfig;
```

Requiring users to add a custom nextconfig is horrible though. Will try to investigate further _why_ this happens in the first place. 
@jornatf Could you test with the above config and see if the error goes away?

**Comment by jornatf** [comment]
@lukasIO It works, thank you!

**Comment by lukasIO** [comment]
Some more findings: 

- the problem doesn't seem to be the `.mjs` extension per se. The components package imports it just fine as .mjs. 
- when only importing livekit-client and none of the components packages, it also just works
- this leads me to believe that it might be connected to the fact that `livekit-client` is a peer dependency 
- another explanation mentioned somewhere in the issues linked above might be that one of our packages imports another esm module which does not use the `.mjs` extension. And that somehow messes with things.

**Comment by lukasIO** [comment]
another workaround: don't use webpack 😬 
when setting `"dev": "next dev --turbo"` as the dev script in package.json, the error goes away, too. No need to adjust the nextjs config then. However that only helps for the dev mode, as there build script would still use webpack and error out with the same failure as before.

**Comment by lukasIO** [comment]
Seems like this is a nextjs bug, starting with 14.0.2.
I raised an [issue in the repo](https://github.com/vercel/next.js/issues/58592) and there are multiple, similar sounding issues open, too

**Comment by avigator003** [comment]
@lukasIO For building the  application same errors coming. And for building there is not such thing called --turbo. In that case is there any resolution as you have given for running the application.

**Comment by lukasIO** [comment]
the only other solution I know is (instead of the config workaround), downgrade nextjs to version `14.0.1`. The bug was introduced in `14.0.2` and is still present in `14.0.3` (which is the current release)

**Comment by lukasIO** [comment]
NextJS PR to fix the issue https://github.com/vercel/next.js/pull/58967

**Comment by zakwear** [comment]
v14.0.4-canary.33 seems to clear it up.

**Comment by lukasIO** [comment]
Next v14.0.4 has been released with the fix. For everyone running into this issue, please upgrade to the latest nextjs version and things should resolve!

**Comment by HQ92** [comment]
I'm getting this same issue on Next 15, any updates on Next 15 compatibility?
