### ISSUE TITLE
Module '"livekit-client"' has no exported member 'createLocalVideoTrack'.

### ISSUE THREAD

**Issue by oldner** [livekit/client-sdk-js#96]
Hello,

When I try to import createLocalVideoTrack from 'livekit-client' it gives me error below. It is same on React example of yours. Other imports works just fine. I looked into src and could not find anything related to createLocalVideoTrack. Here is the screenshot:

![image](https://user-images.githubusercontent.com/48028389/147410449-935d138a-ee75-4eab-bdee-9fd291ae6df1.png)

Error: Module '"livekit-client"' has no exported member 'createLocalVideoTrack'. I am going to use it for the displaying local video of user.

**Comment by jibon57** [comment]
It has been changed in new release https://github.com/livekit/client-sdk-js/releases/tag/v0.15.0. 

`createLocalVideoTrack` -> `LocalParticipant.createTracks({video: true})`

**Comment by davidzhao** [comment]
we'll probably introduce them back in 0.15.1 for backwards compatibility. We've received feedback from others as well of attempting to use it before creating a room.

**Comment by oldner** [comment]
Okay, thanks for your attention.
