### ISSUE TITLE
Problem with setCameraEnabled method on Safari ?

### ISSUE THREAD

**Issue by pork1977** [livekit/client-sdk-js#962]
Hi, I just wanted to report what I think maybe an issue with the setCameraEnabled method (or it could be a Safari browser problem), I'm not entirely sure but thought it was worth reporting anyway.

It seems that when a user is running on Safari (latest version as of today) on either macBook or iPhone, and then another participant disables and re-enables their camera by running setCameraEnabled(false) and then running setCameraEnabled(true), the video doesn't reappear for the user running on Safari. The video disables ok, but it doesn't want to enable again. Hope that makes sense!

When I do the same thing but use Chrome instead of Safari, then it works as expected. Is this something to do with Safari and their rather strict rules do you think?

When doing the same thing using setMicrophoneEnabled(false) and then setMicrophoneEnabled(true) it works perfectly.

I've replicated the problem here using 2 devices.
https://codepen.io/Paul-Wilson-the-bold/pen/RwvdeXO

First user connects on Safari by clicking the button "Join room (user 1)"
Second user connects on another browser like Edge/Chrome by clicking the button "Join room (user 2)"

Afterwards, both users should hopefully see each other. Now, the user **not** running on Safari (user 2) mutes and unmutes their camera by clicking the "Click to mute video" button twice and you'll see the video never reappears for the Safari user.

I realise there are multiple browsers/devices and my tests have primarily been between windows (chrome/edge) and MacBook/iPhone (safari/chrome).

Hopefully the Codepen and the description above is sufficient. Let me know if I've missed anything.

Regards,
Paul

**Comment by lukasIO** [comment]
Hi, what livekit-client version have you tested this with?

**Comment by pork1977** [comment]
Sorry, I forgot to mention that. I've been using this CDN

https://cdn.jsdelivr.net/npm/livekit-client/dist/livekit-client.umd.min.js

**Comment by pork1977** [comment]
Ok thank you. Lower-power mode was off but let me see what I can do with that event and room.startVideo().
Thanks for coming back to me, once I've tried that I'll update you how I get on with it.

**Comment by lukasIO** [comment]
Currently your codepen attaches both mic and video track to the same htmlVideoElement. This is fine generally, but the recommended approach (also due to auto-playback handling) is to give the audio tracks their own htmlAudioElement. That way the htmlVideoElement can stay `muted` which works around a couple of those auto playback issues

**Comment by pork1977** [comment]
Thanks again @lukasIO 
After separating the audio/video and having individual nodes for each seemed to fix the problem.
